[[configuration-printing]]
= Printing content
The `@Button` component can be configured to become a "print button" which opens a printable view of content rendered by a given param path that can easily be printed using the browser's native print dialog window.

[source, java]
----
@Label("Print Demo")
@Button(style = Button.Style.PRINT, printPath = "/domain/page/tile/section")
private String printButton;
----

== Customizing printable content
The rendered printable content can be configured by decorating print button definition with `@PrintConfig`. This allows the configurer the ability to give detailed instructions on how the content should be rendered or how the printing experience should behave.

[source, java]
----
@Label("Print Demo")
@Button(style = Button.Style.PRINT, printPath = "/domain/page/tile/section")
@PrintConfig(useAppStyles = true, closeAfterPrint = false)
private String printButton;
----

Only certain components are allowed to be "printable", such as container-based elements. See the `@PrintConfig` javadocs for more information on which components are able to be printed.

== Controlling the look and feel of printable content
The default behavior of a clicking on a "print button" will open the rendered content in a new browser tab or page with no additional styles added. Styling can be configured by providing additional details for `@PrintConfig`. See the `@PrintConfig` javadocs for more details.