:source-highlighter: prettify
==== Nimbus Search Filtering
Nimbus uses query dsl syntax to construct filtering queries. The framework uses groovy parser to parse the criteria and replace with the required domain name from the library.

==== Usage Examples

Lets take the example domain named TestDSL with an alias "testdsl". 

[[app-listing]]
[source,java,options="nowrap",indent=0]
[subs="verbatim,attributes"]
.TestDSL.java


----
@Getter @Setter
@Domain("testdsl")
@Repo(Database.rep_mongodb)
@Execution.Input.Default
@Execution.Output.Default
@Document
@ToString
public class TestDSL extends IdString{
	@Ignore
	private static final long serialVersionUID = 1L;
	
    private String name;
    private Integer age;
    private LocalDate startDate;
}

----

===== Criteria

If the requirement is to search for all records that have age between 18 and 21, the criteria will be as below

----
&criteria=testdsl.age.between(1,11)
----

The &criteria above denotes a query parameter that will be part of a service task in the BPMN as shown in the below example. 

The search will be executed using the default search operation on the domain and using expression helpers as we have already seen. The complete service task syntax will be

----
${!{_setExternal('/testdsl/_search?b=$execute&criteria=testdsl.age.between(18,21)','<viewPath>')!}}
----

If the requirement is to search for records those have names beginning with 'a' and age between 18 and 21, the criteria is as below

----
&criteria=testdsl.age.between(18,21).and(testdsl.name.startsWith('a'))
----

If the requirement is to search for records those have names beginning with 'a' or age between 18 and 21, the criteria is as below

----
&criteria=testdsl.age.between(18,21).or(testdsl.name.startsWith('a'))
----

If the requirement is to search for records that have a start date as today's date, the criteria is as below

----
&criteria=testdsl.startDate.eq(todaydate)
----

Please note that 'todaydate' is a keyword that is used by framework's groovy parser to parse it to actual date.

===== Projection
The framework provides for support for certain projections. 
If the requirement is to fetch the count of all records

----
${!{_setExternalParam('/testdsl/_search?b=$execute&projection=count','<viewpath>')!}}
----

If the requirement is to get the count of records that have a start date as today's date, the criteria is as below

----
&criteria=testdsl.startDate.eq(todaydate)&projection=count
----