The `@Grid` component can be used to display tabular data within an HTML table. As the `table` itself can 
be configured in a variety of ways, so too can the `@Grid` component.

.Grid Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|alias |String | Grid |cannot be changed
|isTransient |boolean |false | specify the behaviour of CardDetailsGrid during page load
|expandableRows | boolean | false | whether or not expandable rows should be enabled
|onLoad |boolean |false | specify the behaviour of CardDetailsGrid during page load
|rowSelection |boolean |false | determine if row selection is enabled on the Grid
|pageSize |String | 10 |specify the page size for the Grid
|pagination |boolean |true | determine if pagination is enabled on the Grid
|postButton |boolean |false | determine if post Button is enabled on the Grid
|postButtonUrl |String |  |specify the url of post button for the Grid
|postButtonTargetPath |String |  |Target path for the multi select rows on the grid. The payload for the selections will be created based on this path.
|postButtonAlias |String |  | Button name alias for the multiselect action on the grid
|postButtonLabel |String |  | Button label to be used on the post button
|postEventOnChange |boolean | false |post the value to the server onblur
|url |String |  |specify url for the Grid

|=========================================================

.Configuring the @Grid component
In the example below, we can see a typical structure for using `@Grid`.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Grid
private List<PetLineItem> pets;
----

.Configuring the @Grid component with multiple row selection
In the example below, we can see an example of configuring a grid that should allow the user to select multiple 
rows and then perform some action with those selections.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
// Provide the postButtonUrl based on the config.
@Grid(rowSelection=true,
        postButtonUrl="/view/page/tile/section/remove",
        postButton=true,
        postButtonTargetPath="temp_ids",
        postButtonAlias="Remove")
@Path("/members")
private List<VGGroupView> vgGroupList;

@Configs({
    @Config(url="/page/tile/section/vsRemoveList/_replace"),
    @Config(url="/page/tile/section/vgGroupList/<!col!>/.m/_process?fn=_setByRule&rule=updategroup", col="<!/vsRemoveList/temp_ids!>"),
    @Config(url="<!#this!>/../vgGroupList.m/_process?fn=_set&url=/p/group/_search?fn=query&project=/members")
})
private String remove;

private VSRemoveList vsRemoveList;

@Getter @Setter
public static class VSRemoveList {
	private List<String> temp_ids;
}
----

// TODO - Write an explanation for the black magic that is coded above.

[discrete]
===== Controlling column data with @GridColumn

The `@GridColumn` component has been introduced to provide control over the individual params displayed on
the `@Grid`. `@GridColumn` will be recognized when used within the _generic class_ of a collection that has been 
annotated with `@Grid`.

.GridColumn Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|alias |String | GridColumn |cannot be changed
|hidden |boolean |false | Setting this to true will hide the column in the grid
|sortable |boolean |false | Enables sorting on the column
|filter |boolean | false |Setting this to true will enable a explicit filter component(Input TextBox) on the UI
|filterValue |String | | Default filterValue for a particular column.Can be used without setting filter attribute to restrict user from providing any other filter value.
|filterMode |String | equals |Mode to filter data within the column. It is defaulted to 'equals'.Current filter modes supported by the Grid component are listed as enum values - equals,contains,endsWith,in

|=========================================================

.Configuring the @GridColumn component
In the example below, we can see a typical structure for using `@GridColumn`.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Grid
private List<PetLineItem> pets;

@MapsTo.Type(Pet.class)
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    @MapsTo.Path
    private String petName;
}
----

In this scenario, `PetLineItem` is the _generic class_ of our collection `pets` and `petName` is represents the 
column entry of the data displayed in the HTML table.

This example does not really showcase the usage of what 
`@GridColumn` can do, but is more intended to show a structure of what a typical object might look like. More 
examples will be provided below to show scenarios where we can leverage it to provide control over the column.

NOTE: `@GridColumn` is not required to be present in order to render the param on the UI. Adding it simply supplies
the user with more control.

.Hiding a Column from being displayed
Consider the scenario where we want to keep a param in the _generic class_ of a collection decorated with `@Grid`, 
but we do not want that param to be displayed as a column in the HTML table.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@MapsTo.Type(Pet.class)
@Getter @Setter
public static class PetLineItem {

    @GridColumn(hidden = true)
    @MapsTo.Path
    private String id;

    @GridColumn
    @MapsTo.Path
    private String petName;
}
----

In this scenario, only `petName` will be displayed in the rendered HTML table. The `id` param is hidden as a result of
`hidden = true`.
