[cols="4,^3,^3,10",options="header"]

A hyperlink component used for navigation or user interaction of text.

Links can currently be used under the following components:

* CardDetail
* Menu
* Section

'''

.Link Attributes
|=========================================================
| Name					| Type 			| Default 				| Description

| altText 				| String 		|  						| alternate text to be used
| b 					| String 		| $executeAnd$nav		| behavior to use
| cssClass				| String 		|  						| class used to style the component
| imgSrc 				| String 		|  						| source path/ url of the image
| method 				| String 		| GET 					| HTTP method that will be executed
| rel					| String		|						| the HTML rel attribute
| target				| String		|						| the HTML target attribute
| url 					| String 		| 		 				| source url to operate on
| value 				| Enum (Type)	| Type.Default			| classification of the link useful for determining functional behavior

|=========================================================

.Type.java
NOTE: The possible enum values for value are: *DEFAULT, EXTERNAL, MENU*.


[source,java,indent=0]
[subs="verbatim,attributes"]
.Link.java
----
// UI Navigation to page vpHome under domain petclinic
@Link(url="/h/petclinic/vpHome")
private String linkToHome;

// Executes a request against _subscribe, and sets the image
@Link(url="/notifications/_subscribe:{id}/_process", b="$executeAnd$configAnd$nav" , method="POST")
private String subscribeToEmailNotifications;

// Creates an external link, as in a link navigating outside of the context of the Nimbus framework.
@Link(url="https://www.mywebsite.com", value = Link.Type.EXTERNAL, target="_new", rel="nofollow")
private String myWebsiteLink;
----
