.Modal Attributes
[cols="3,^2,^2,^2,10",options="header"]
|=========================================================
| Name 		| Type 		| Default 		| Required 	| Description

| alias 	| String 	| Modal 		| Y			| Cannot be changed.
| closable	| boolean	| false			| Y			| Specify whether the modal window can be closed.
| context	| ParamContext | @ParamContext(enabled = true, visible = false) | N | Specify the default contextual properties.
| cssClass 	| String	| 				| N			| Override default class.
| title		| String	| 				| N			| Title for the Modal window.
| type 		| Type 		| Type.dialog 	| Y			| Types of modal can be a dialog or a slider.
| width		| String	| 500			| Y			| Width of the modal window

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Modal.java
----
@Modal
private VMMyTasks vmMyTasks;
----

NOTE: Modal is supported only in a tile

[discrete]
===== Setting @Modal to be displayed by default
Modal makes use of **@ParamContext** to by default render it's visible property to false during initialization. We can override this
functionality by providing our own unique **@ParamContext** values as a parameter of **@Modal**.
----
 public static class SampleView {

    @Modal(context = @ParamContext(enabled=true, visible=true))
    private MyModal myModal;

    public static class MyModal { ... }
 }
----
In this example, we are creating a modal _myModal_ who's visible property will be true on initialization, and hence will be displayed
when the corresponding page is rendered.