[[domain-model-definition-structure]]
= Defintion Structure

[discrete]
== Simple Domain Models
The `Person` _domain model_ previously defined is a representation of what is understood to be a _simple domain model_. A _simple domain model_ is one who's field data does not contain other _domain model_ types. In other words, it's defined fields consist only of simple types.

While not always the case, simple domain models are typically associated with _core domain models_.

[discrete]
== Complex Domain Models
The Framework supports the notion of "nesting" _domain models_ within each other. 

Consider the following example of a _view domain model_ representing a form for the aforementioned `Person`:

[source,java]
.Person.java
----
@Model
@Getter @Setter @ToString
public class VFPersonForm {

    @TextBox
    private String firstName;

    @TextBox
    private String lastName;

    private Address address;
}
----

[source,java]
.Address.java
----
@Model
@Getter @Setter @ToString
public class Address {
    
    @TextBox
    private String line1;
    ...
}
----

In this example, both `VFPersonForm` and `Address` are decorated with `@Model`. Therefore, `VFPersonForm` is a _complex domain model_ because it contains an instance of `Address`.

This scenario contains only one level of nesting between `VFPersomForm` and `Address`. It is not uncommon to have multiple layers of "nesting" within a _domain model_, hence giving rise to the term _complex_. Consider a common scenario in HTML where a page contains a section, which contains a tab, which contains a component, which contains a... the context of what could be rendered in the view could be boundless. The Framework is able to support this via "nesting" and using these _complex domain models_.

While not always the case, complex domain models are typically associated with _view domain models_.