[[domain-model-domain-load]]
= Loading the Domain Entities

On application startup, the Framework consumes the defined _domain model_ configurations and stores the all of the instructions included within them in memory. The `com.antheminc.oss.nimbus.domain.config.builder` package is the primary consumer of this information during the initial loading process, with the starting point being with the `DomainConfigBuilder`.

The `DomainConfigBuilder` uses the Spring Framework's scanning capabilities to retrieve `Domain` configuration defined within specific packages. The packages that are scanned in this manner can and should be defined via the application properties using the standard Spring `PropertyPlaceholderConfigurer` mechanism (using _application.properties_, _application.yml_, etc.). 

The owning property used to identify packages for scan is: `domain.model.basePackages`.

.Configuring Base Packages to Load Domain Entities
[source,yaml]
----
domain:
  model:
    basePackages:
      - com.antheminc.oss.nimbus.entity
      - com.acme.app.model.feature_a.core
      - com.acme.app.model.feature_a.view
      - com.acme.app.model.feature_b.core
      - com.acme.app.model.feature_b.view
----

NOTE: The order of which the entities are loaded may play an impact on certain framework features. It is recommended to always load _core_ domain config prior to _view_ domain config.