[[view-config-annotation-grid]]
= Grid

Grid is a table container capable of displaying tabular data.

.Allowed Parent Components
<<view-config-annotation-form>>, 
<<view-config-annotation-section>>

.Allowed Children Components
`@Grid` should decorate a field having a collection/array with a defined type. The defined type is treated as the definition for the row data in the rendered HTML table. This is referred to as the _collection element type_. The allowed children components of the collection element's type are:

<<view-config-annotation-grid-column>>, 
<<view-config-annotation-link-menu>>, 
<<view-config-annotation-grid-row-body>>

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@Grid(export=true)
private List<PetLineItem> vgPets;

@Model
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    private String field1;

    @LinkMenu
    private VLMMain vlmMain;

    @GridRowBody
    private ExpandedRowContent expandedRowContent;

    @Model
    @Getter @Setter
    public static class VLMMain { ... }

    @Model
    @Getter @Setter
    public static class ExpandedRowContent { ... }
}
----

== Multiple row selection
`@Grid` offers the ability to select multiple rows of data and submit the indexes of the selected rows as JSON data to the server for processing.

To enable this feature, the following attributes must be set:

* `rowSelection` = `true`
** renders a checkbox at the beginning of each row in the table for row selection
* `postButton` = `true`
** renders a button below the rendered `@Grid` that when clicked, submits an HTTP POST request with a payload containing the selected index to the path at `postButtonUri`
* `postButtonUri`
** a parameter path relative to the decorated `@Grid` parameter to invoke an HTTP POST request on with the selected indexes
* `postButtonTargetPath`
** the key to be used for the JSON object sent as a payload
* (Optional) `postButtonLabel`
** controls the label of the button rendered by `postButton`
* (Optional) `headerCheckboxToggleAllPages`
** when `true`, selecting the "select all" checkbox in the header of the `@Grid` will select all the records in the dataset across all pages. When `false`, only within the current page items will be selected
* (Optional) `export`
** exposes the capability to download the grid data in .csv format

.Example configuration for multiple row selection using @Grid
[source, java]
----
@Grid(onLoad = true, rowSelection = true, postButton = true, postButtonUri = "../actionRemove", postButtonTargetPath = "ids", postButtonLabel = "Remove")
@Path
@Config(url = "/p/member/_search?fn=example")
private List<MemberLineItem> membersGrid;

@Config(url = "/page/tile/section/selectedIdsWrapper/_replace") //<1>
@Config(url = "/p/member:<!/../membersGrid/<!col!>/memberId!>/_delete", col = "<!/selectedIdsWrapper/ids!>") //<2>
private String actionRemove;

private SelectedIdsWrapper selectedIdsWrapper;

@Model
@Getter @Setter
public static class SelectedIdsWrapper {
	private List<String> ids;
}

@MapsTo.Type(Member.class)
@Getter @Setter
public static class MemberLineItem { ... }
----

In this example, assume there are ten rows of data and the user selects indexes 1, 3, and 7 (Indexes are zero based). When clicking the `"Remove"` button, the an HTTP POST call is sent to the param at `actionRemove` with the payload:

```json
{
    "ids": ["1", "3", "7"]
}
```

Next, the `@Config` statements decorating `actionRemove` are executed. Config **#1** uses `_replace` to update the `sepectedIdsWrapper` `ids` field to be `["1", "3", "7"]`. Config **#2** is a bit trickier to read, but it iterates over the values just set into `"selectedIdsWrapper/ids"` and for each id, retrieves a record from `membersGrid`. From that point, the object in context is a `MemberLineItem` object, from which `memberId` is retrieved and used with `_delete` to delete the selected members them from the `member` domain.

.Exporting grid content
The attribute export=true instructs the grid component to show an 'export' link (clicking of which the grid data can be exported).
There are 2 kinds of scenarios where the export of grid data can be used. 
1. When grid is configured to use client side pagination, the export funtionality would export all the data to a csv file that gets downloaded on the machine.
2. When the grid is configured with server side pagination, the export functioanlity would export only the current page data.

NOTE: The data downloaded would be in CSV format.

== Using inline edit for @Grid records
`@Grid` supports inline editing, allowing the user to edit the first-level visible fields in a table row.

[source, java]
----
@Grid(editRow = true) <1>
private List<SampleLineItem> editableGrid;

@Model @Getter @Setter
public static class SampleLineItem {
    
    private String _action_onEdit; <2>

    // Line item fields below here
}
----
<1> Toggling the attribute `editRow` will enable/disable an edit icon which will make a `_get` request parameter defined by `onEdit`.
<2> Decorate `_action_onEdit` with any `@Config` or framework supported annotations.

== Configuring server side pagination
By default, if the the `@Grid` component is configured to use pagination, it uses client side pagination. The rendered table can be configured to work with the framework by providing Command DSL statements that the framework then interpolates and hands off to Spring to take advantage of it's rich server side pagination features.

Certain pagination specific query parameters can be used to leverage framework support.

.Pagination Query Parameters
[horizontal]
`page` :: An integer representing the starting page number
`pageSize` :: An integer for the number of elements to display per page
`sortBy` :: A "key:value" string with the `key` representing the field over which to sort and the `value` representing the sort direction. Supported values are determined by the `org.springframework.data.domain.Direction` (`asc`, `desc`, etc.)

.Server side pagination example
[source, java]
----
@MapsTo.Path(linked = false)
@Grid(onLoad = true, pageSize = "3", lazyLoad = true) <1>
@Config(url = "/vpVisitsServer/vtVisits/vsVisits/visits.m/_process?fn=_set&url=/p/visit/_search?fn=example&<!page=y!>") <2>
private List<VisitLineItem> visits;
----

Setting `lazyLoad = true` as seen in <1> informs the client side to use server side pagination by sending Command DSL statements to the server. The client side will send pagination information as query parameters and payload data depending upon the action taken upon the rendered `@Grid` component.

Setting `<!page=y!>` as seen in <2>, invokes the <<param-pathing-variable-resolver>> to construct/pass along any query parameters/payload data sent from the incoming Command DSL statement for the _pagination query parameters_. For example, the following statement:

`http://localhost:8080/client/org/app/p/visitview/vpVisitsServer/vtVisits/vsVisits/visits/_get?b=$execute&pageSize=5&page=0`

would result in <2> being invoked as:

`/vpVisitsServer/vtVisits/vsVisits/visits.m/_process?fn=_set&url=/p/visit/_search?fn=example&page=0&pageSize=5`

[NOTE]
When serverside pagination is enabled and `<!page=y!>` is given, it is expected that `\_get` calls invoking the parameter would also send the pagination query parameters, otherwise pagination will not work as expected.

.Sorting with server side pagination
Server side sorting can be achieved by setting `sortBy` as a query paremeter in the Command DSL statement.

`/vpVisitsServer/vtVisits/vsVisits/visits.m/_process?fn=_set&url=/p/visit/_search?fn=example&page=0&pageSize=5&sortBy=firstName:DESC`

.Filtering with server side pagination
Server side filtering can be achieved by setting the `filters` JSON in the raw payload alongside the Command DSL statement.

Request URL: `/vpVisitsServer/vtVisits/vsVisits/visits.m/_process?fn=_set&url=/p/visit/_search?fn=example&page=0&pageSize=5`

Payload:
[source, json]
----
filters: [
    {
        "code": "firstName", 
        "value": "bob"
    }
]
----

[[view-config-annotation-grid-column]]
= GridColumn

GridColumn is a container for displaying a single value within a <<view-config-annotation-grid>>.

.Allowed Parent Components
<<view-config-annotation-grid>>

.Allowed Children Components
None. `@GridColumn` should decorate a field having a simple type.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@Model
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    private String field1;
}
----

[[view-config-annotation-grid-row-body]]
= GridRowBody

GridRowBody is used to display additional content about the row data within a <<view-config-annotation-grid>>.

.Allowed Parent Components
<<view-config-annotation-grid>>

.Allowed Children Components
`@GridRowBody` will display children components in the same manner as <<view-config-annotation-section>> does. See the _Allowed Children Components_ of <<view-config-annotation-section>> for more details.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@MapsTo.Type(Pet.class)
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    @Path
    private String name;

    @GridRowBody
    private ExpandedRowContent expandedRowContent;

    @Model
    @Getter @Setter
	public static class ExpandedRowContent {
		
		@CardDetail
		private CardDetails cardDetails;
	}
	
	@Model
    @Getter @Setter
	public static class CardDetails {
		
		@CardDetail.Body
		private CardBody cardBody;
	}
	
	@Model
    @Getter @Setter
	public static class CardBody {
		
		@FieldValue
        @Path
		private String id;
	}
}
----
