[[view-config-annotation-grid]]
= Grid

Grid is a table container capable of displaying tabular data.

.Allowed Parent Components
<<view-config-annotation-form>>, 
<<view-config-annotation-section>>

.Allowed Children Components
`@Grid` should decorate a field having a collection/array with a defined type. The defined type is treated as the definition for the row data in the rendered HTML table. This is referred to as the _collection element type_. The allowed children components of the collection element's type are:

<<view-config-annotation-grid-column>>, 
<<view-config-annotation-link-menu>>, 
<<view-config-annotation-grid-row-body>>

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@Grid(export=true)
private List<PetLineItem> vgPets;

@Model
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    private String field1;

    @LinkMenu
    private VLMMain vlmMain;

    @GridRowBody
    private ExpandedRowContent expandedRowContent;

    @Model
    @Getter @Setter
    public static class VLMMain { ... }

    @Model
    @Getter @Setter
    public static class ExpandedRowContent { ... }
}
----

== Multiple row selection
`@Grid` offers the ability to select multiple rows of data and submit the indexes of the selected rows as JSON data to the server for processing.

To enable this feature, the following attributes must be set:

* `rowSelection` = `true`
** renders a checkbox at the beginning of each row in the table for row selection
* `postButton` = `true`
** renders a button below the rendered `@Grid` that when clicked, submits an HTTP POST request with a payload containing the selected index to the path at `postButtonUri`
* `postButtonUri`
** a parameter path relative to the decorated `@Grid` parameter to invoke an HTTP POST request on with the selected indexes
* `postButtonTargetPath`
** the key to be used for the JSON object sent as a payload
* (Optional) `postButtonLabel`
** controls the label of the button rendered by `postButton`
* (Optional) `headerCheckboxToggleAllPages`
** when `true`, selecting the "select all" checkbox in the header of the `@Grid` will select all the records in the dataset across all pages. When `false`, only within the current page items will be selected
* (Optional) `export`
** exposes the capability to download the grid data in .csv format

.Example configuration for multiple row selection using @Grid
[source, java]
----
@Grid(onLoad = true, rowSelection = true, postButton = true, postButtonUri = "../actionRemove", postButtonTargetPath = "ids", postButtonLabel = "Remove")
@Path
@Config(url = "/p/member/_search?fn=example")
private List<MemberLineItem> membersGrid;

@Config(url = "/page/tile/section/selectedIdsWrapper/_replace") //<1>
@Config(url = "/p/member:<!/../membersGrid/<!col!>/memberId!>/_delete", col = "<!/selectedIdsWrapper/ids!>") //<2>
private String actionRemove;

private SelectedIdsWrapper selectedIdsWrapper;

@Model
@Getter @Setter
public static class SelectedIdsWrapper {
	private List<String> ids;
}

@MapsTo.Type(Member.class)
@Getter @Setter
public static class MemberLineItem { ... }
----

In this example, assume there are ten rows of data and the user selects indexes 1, 3, and 7 (Indexes are zero based). When clicking the `"Remove"` button, the an HTTP POST call is sent to the param at `actionRemove` with the payload:

```json
{
    "ids": ["1", "3", "7"]
}
```

Next, the `@Config` statements decorating `actionRemove` are executed. Config **#1** uses `_replace` to update the `sepectedIdsWrapper` `ids` field to be `["1", "3", "7"]`. Config **#2** is a bit trickier to read, but it iterates over the values just set into `"selectedIdsWrapper/ids"` and for each id, retrieves a record from `membersGrid`. From that point, the object in context is a `MemberLineItem` object, from which `memberId` is retrieved and used with `_delete` to delete the selected members them from the `member` domain.

.Exporting grid content
The attribute export=true instructs the grid component to show an 'export' link (clicking of which the grid data can be exported).
There are 2 kinds of scenarios where the export of grid data can be used. 
1. When grid is configured to use client side pagination, the export funtionality would export all the data to a csv file that gets downloaded on the machine.
2. When the grid is configured with server side pagination, the export functioanlity would export only the current page data.

NOTE: The data downloaded would be in CSV format.

[[view-config-annotation-grid-column]]
== GridColumn

GridColumn is a container for displaying a single value within a <<view-config-annotation-grid>>.

.Allowed Parent Components
<<view-config-annotation-grid>>

.Allowed Children Components
None. `@GridColumn` should decorate a field having a simple type.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@Model
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    private String field1;
}
----

[[view-config-annotation-grid-row-body]]
== GridRowBody

GridRowBody is used to display additional content about the row data within a <<view-config-annotation-grid>>.

.Allowed Parent Components
<<view-config-annotation-grid>>

.Allowed Children Components
`@GridRowBody` will display children components in the same manner as <<view-config-annotation-section>> does. See the _Allowed Children Components_ of <<view-config-annotation-section>> for more details.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@MapsTo.Type(Pet.class)
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    @Path
    private String name;

    @GridRowBody
    private ExpandedRowContent expandedRowContent;

    @Model
    @Getter @Setter
	public static class ExpandedRowContent {
		
		@CardDetail
		private CardDetails cardDetails;
	}
	
	@Model
    @Getter @Setter
	public static class CardDetails {
		
		@CardDetail.Body
		private CardBody cardBody;
	}
	
	@Model
    @Getter @Setter
	public static class CardBody {
		
		@FieldValue
        @Path
		private String id;
	}
}
----
