[[function-handler-process-filter]]
= Filter
The filter function handler attempts to set the state of a given <<param-state-introduction-collection>> to the result set obtained by removing collection elements do not meet a truthful evaluation of a given SpEL predicate.

[NOTE]
====
* The action parameter must be a collection or array typed `Param`, and is by default the `Param` given in the preceding Command path.
* The action paremeter to set may be overriden by supplying a path to the query parameter: `targetParam`.
====

== Usage

.Examples
[source,java]
----
@Domain(value = "sample_view", includeListeners={ ListenerType.websocket })
@MapsTo.Type(SampleCoreEntity.class)
@Repo(Database.rep_none)
@Getter @Setter
public class VRSampleViewRootEntity {

    private String[] arr;
    private List<String> simple_list;
    private List<ComplexObject> complex_list;

    @Config(url = "/arr/_process?fn=_filter&expr=contains('pickme')")
    @Config(url = "/simple_list/_process?fn=_filter&expr=contains('pickme')")
    @Config(url = "/complex_list/_process?fn=_filter&expr=state.p1.contains('pickme')")
    private String action_demoFilter;

    @Model 
    @Data 
    public static class ComplexObject {
        private String p1;
    }
}
----

.Filtering complex vs non-complex typed collections
The expected SpEL predicate syntax is slightly different when the action parameter's collection element type is complex versus when it is not. Non-complex elements will simply expose each collection element's state to the SpEL expression context, while complex elements will expose the entire Param for each collection element.

.Non-complex typed collection
[source,java]
----
@Config(url = "/simple_list/_process?fn=_filter&expr=contains('pickme')")
----

Since `simple_list` has type `String`, it is non-complex. Notice in this example that `expr` is making use of the `String.contains` method. This is because the state of the collection element (type `String`) is exposed as the _context_ for the SpEL expression.

.Complex typed collection
[source,java]
----
@Config(url = "/complex_list/_process?fn=_filter&expr=state.p1.contains('pickme')")
----

Since `complex_list` has type `ComplexObject`, it is complex. For complex typed collections, the `Param` interface for the collection element parameter is exposed as the _context_ for the SpEL expression, which offers the ability to reference `state`. In this way, greater filtering support is available for complex elements.

== Supported Query Parameters
[cols="2,2,8"]
|===
| Name | Required | Description
| expr | true | A SpEL expression to evaluate to determine whether or not a collection element should be included in the final result set.
| targetParam | false | The path to the param to set the final result set into. The type of the `targetParam` should match that of the collection element being filtered. If not provided, the state will be set into the _action parameter_.
|===

