[[param-state-introduction]]
= Introduction

After the framework registers domain entity definitions during application startup, it is creating what the Framework understands as a `Param`. The `Param` interface defines a number of properties on it that both the framework and UI framework will use to perform a given operation. Some examples might be, setting the value of the object, setting the object's visibility, or setting whether or not the object should have validation applied to it (if it is a form element). Whatever the case, the important thing to note is that the `Param` interface is collectively the "model" data that is used everywhere throughout the Framework.

While understanding the core concepts of the `Param` is not essential for building out the UI of the application, it is important to understand it when dealing with certain functional scenarios. For example, an application can be created using the Framework by simply using the <<view-config-annotations>> and <<config-annotations-conditional>>; however, when needing to manipulate the model directly (perhaps in a rule or SpEL expression), having an understanding of `Param` will be extremely useful. 