[[param-pathing]]
= Pathing

As previously explained, every Java variable created under a domain entity definition will eventually result in the creation of a _param_. Each param that is created in this way has a unique *path* by which it can be identified through using the framework's Command Query DSL.

== Introduction
The path is represented as a URI address that uniquely identifies a param's location within the Framework. It is built by traversing through a Java class's members, with a `/` denoting a child member (child members are also often referred to as "nested" members).

An example of some param paths can be found in the sample code below:

[source, java]
----
@Domain("petshop")
@Getter @Setter
public class PetShop {

    // Param Path: /petshop:1/name
    private String name;

    // Param Path: /petshop:1/address
    private Address address;

    // Param Path: /petshop:1/boardedPets
    private List<Pet> boardedPets;

    // Collection elements are also retrievable by supplying an index
    // immediately following member name.
    // Collection Element Param Path with index 0: 
    //   /petshop:1/boardedPets/0
    // Collection Element Param Path with index 1:
    //   /petshop:1/boardedPets/1
    // Collection Element Param Path with index n (where n is an 
    // integer >= 0): 
    //   /petshop:1/boardedPets/n

    @Model
    @Getter @Setter
    public static class Address {

        // /petshop:1/address/street
        private String street;

        ...
    }

    @Model
    @Getter @Setter
    public static class Pet {

        // /petshop:1/boardedPets/0/name
        // /petshop:1/boardedPets/1/name
        // /petshop:1/boardedPets/.../name
        private String name;

        ...
    }
}
----

Please note that in the example above all of the provided param paths are of the form: `/*petshop:1*/...`. The index `1` is known as a `*refId*`, which will be explained in the following section.

== RefId
A _refId_ is a unique identifier used to identify a particular instance of _domain entity_ that has been created.

////
TODO More explanation!
////

== Path Variable Resolver

The Command Query DSL offers certain reserved variables or keywords that can be used in a path. The Framework uses a default implementation of `CommandPathVariableResolver` to resolve a param path from a provided <<param-pathing-context>>.

=== Param Context
[[param-pathing-context]]

NOTE: This section is a work in progress.

////
TODO Explain why context matters when resolving param paths
////

=== Property Placeholders

The default implementation of `CommandPathVariableResolver` will attempt to first resolve `${...}` placeholders in the given path, replacing them with corresponding property values. Unresolvable placeholders with no default value is not supported.

=== Reserved Keywords
After resolving property placeholders reserved framework keywords will be resolved. The framework provides support for the following reserved keywords:

////
TODO There are some buzzwords in the table below. Let's move them to their own dedicated section and link them so it makes sense for non-experienced users.
- full URL
- switching param contexts
- mapped param
- root domain param
////

[cols="2, 14"]
|===
| Keyword | Description

| `/p` | Denotes the start of the param path. This is only needed to be given when using a full URL or switching param contexts.
| `/.m` | Resolves to the path of the param that is mapped to the param identified by the preceeding path. (e.g. `PARAM_PATH/.m` returns the mapped param of the param identified by `PARAM_PATH`.
| `/.d` | Resolves to the path of the param that is the root domain of the param identified by the preceeding path. (e.g. `PARAM_PATH/.d` returns the domain param that owns the param identified by `PARAM_PATH`.
| `<!#elemId!>` | 
| `<!#env!>` | 
| `<!#refId!>` | 
| `<!#self!>` | 
| `<!#this!>` | Resolves to the path of the param in the current context.
|===