[[appendix-release-notes-1.2.0-M1]]
= 1.2.0-M1

* **General Changes**
** link:../index.html#configuration-validation[Validation]
*** Validation messages for `javax.validation.constraints` annotations now receive their default message values from the server
**** Default Framework validation messages can be overriden by defining key/value pairs in application.yml. (See link:../index.html#configuration-validation-messages[Validation Messages])

* **Core Config Annotations**
** N/A

* **View Config Annotations**
** Fixed an issue where components defined within layout were not always updating when navigating between pages.

////
1. Run: git log PREVIOUS_TAG_ID..HEAD –oneline
2. Copy contents to VSCode
3. Pretty Format the commits by doing a Find/Replace in VSCode
     Find: (^.{9}) (.*)
     Replace: * https://github.com/openanthem/nimbus-core/commit/$1[$2 ($1)]
////
== Change History

The following commit history below represents all commits in this version not found in the previous version (in descending order):

0b194d21d (HEAD -> 1.2.x, upstream/1.2.x) Merge pull request #320 from sandeepmantha/1.2.x
c7cdb9be5 remove specific component check

4ec3e4f32 defect fix for nested collection updates


300e517fe (origin/bugfix/removeZdtChanges, bugfix/removeZdtChanges) Revert "ParamUtils Refactor"
963193307 Revert "Fixed ZonedDateTime issue not storing browser timezone"
922457e76 test case fix
882d07df3 (origin/bugfix/zdt, bugfix/zdt) Test case fix


0050050f0 NIM-21231: Fixing @Grid expandable feature
38c5e2d3b update to link component
c47bd74b0 link component dynamic value fix for a grid - 20606
8013be87b 26608 - counter message to consider all validations on required fields


effdc6b61 code cleanup

0b5ec954f Fixed validation message prioritization bug
3c761c761 Silencing UI error for unimplemented validators
44ebf4ec9 NIM-18855: Adding Default UI Validations to Server Config
56e2894c6 created test cases




0e333f9d0 New annotation config handler impl for event annotations
a728b41f5 flexbox styles

0d54ea797 Adds option to create event annotations where actual event(s) binding is configurable
9d6127d92 Adding run-ui-tests plugin back
20bcf1d32 NIM-21053: Fixes Layout Update Issue

25439a221 Fixes applyValueStyles space replacement issue

8d2bdbf2a updated test case scenarios

4e6f5caa0 Uncheck all the checked rows onFilter event - this is to prevent keeping old rows that may not be on current page checked based on current filter criteria. Also will prevent them from being submitted on postevent.

efcbc5d79 NIM-20992, Lookup Search Improvements
2e93d2cd8 updates method name
f938f47f8 NIM-20846

13ff3d38c Removing ng execution from run-ui-tests
8beee6d34 Next Development Version

5869df947 created testcase scnerios



f18194365 Reverting run-ui-tests changes
31fb72a83 run-ui-tests to execute ng from node_modules/.bin

9951d66d0 Correcting the comments

c060c96a8 added webdriver

9057e786b remove unused import
588f963a8 updated beforeach() in spec files
3d3788e9b Resolving merge conflict


7581e08bd code cleanup
a2eaa5885 fixed failing testcase

0a45e3306 fixed failing testcases


9934e2f0d Adding isEmpty() for Param
78526bb54 Polish

e8a30fc25 clean up of button, eventpropagation + table postbuttonurl null fix
3974c093b Adding back the logic for the deprecated attribute postButtonUrl. Will remove in future versions when the server side annotation is completely removed.
5bc09d5c0 Removing server side GridStateHandler changes
49f987071 fixing merge conflicts

67459c497 null check for grid's row selection + modal positioning
bd71da581 event propagation on button + modal fix for random moving
230661067 Numerous ViewConfig Javadoc Updates


e91217324 remove commenting
1cc832154 prevent doubleclick of button
876d98a20 lombok v1.16.20 requires a new property to generate @ConstructorProperties

41de8a002 Update pom.xml
304b91248 Update pom.xml
710791031 Update pom.xml
adb026d95 Update pom.xml
f2425f8e4 Update pom.xml
88e0d3106 Update pom.xml
cbeb9dca3 Update pom.xml
45036f757 layout fix


a9edbfb16 test case refactor
0ed52d88d Polish
534e01e36 nav bar freezing

e67ffb984 Documentation

ca44aece2 Removing console log statement

b6cf61f10 lombok v1.16.20 requires a new property to generate @ConstructorProperties

43abbed79 fixed layout


c3345d808 Making @PageHeader(Property.LOGO) img optional
88fd9139b Console logging cleanup
93ec2fcc5 Replacing throw statements with logs
feb0e3299 Fixed ZonedDateTime issue not storing browser timezone
e568e07b1 ParamUtils Refactor
e80b9062e update sass version

5c1cb833c Enable caching for staticcodevalue dao search

b938f9688 Server and UI changes for resolving dynamic url

57ccb67f7 Set PrimeNG version
9bd3bfe73 Set PrimeNG version
1fc9a3629 Updating Framework Version
9cca65cff Next Development Version


ca0217f64 updated test cases
52cd8328e (tag: 1.1.9) Merge pull request #275 from lopezton-anthem/bugfix/1.1.9
f4cc07be0 Null safety check

611a5329a exclude base packages with test cases

e6cef1f39 updated component spec files

9e289edf8 1. revertes - adds command exec id (unique id) for loggin interceptor to help indentify input/output of commands that contain sub commands - will include this in the next PR
5aa6288bb 1. resolves @Values url relative to root command. 2. adds command exec id (unique id) for loggin interceptor to help indentify input/output of commands that contain sub commands
a3302230a fix for no scrolbar on modal due to primeng code change
bca811f57 Unsubscribing from print directive only when necessary
8383d09d9 Null safety check

85172c840 Fixing an issue where @Modal scrolled to button on load
bce848179 Support for @ValuesConditional and non-string types
07d4ce7aa Revert "Reverting exception throw on _get call without refId"
0db7fda7e Reverting exception throw on _get call without refId
de7414169 fix for modals freezing on UI due to core update
91e324ec3 bugfix - carddetail grid not showing up with fieldvaluegroup

3f4a4c756 NIM-20529 counter message update
6d0406e97 _update fix for collections


4b3026924 Table Column style override Capability. Throw error when a _get call happens without a refId

6b2de4a02 Print support modifications
9d675de6f Ui Styles for Signature and Table Column. Check for null refId and throw Exception in _get call.



ead29c0d0 Renaming attribute

d9e661993 Adding @printable to support printing DOM content
d41a9d506 Fixing an issue where @Modal scrolled to button on load


80b0831c3 Adding missed file in app.module.ts
0e80f474f NIM-19755 - replace "null" param values to null

21b9d6032 Next Release Version 1.1.9
2051c0555 Next Development Version
be145d065 Adds missing import for BaseTableElement


eda887894 NIM-19755 - replace "null" param values to null

54f04ff43 Adding Support for @LinkMenu to @TreeGrid


a072cd717 Adding dynamic label support to @Modal
0f1dd13ad Deprecating @Grid dataKey attribute

436373f7b _update fix for collections
833c99773 setbyrule test case

570eb6d72 Next Development Version

ff241b04e cleaning up unused date control
51884e4e1 form control refactor
df8c81152 Next Development Version: 1.1.8

cb416cd2c null safety checks
558343e3a Removing printout statement
bced2518d form refactor

835271755 Fixes @Ignore(listenertype = websocket) to not send the paramConfig to json clients

744056d40 sass  version update
68597bb93 removing form visible flag
82538f929 hide just label instead of form component

b082355cf Support for @ValuesConditional and non-string types

fe796d8ee version update to 1.1.7
cf13e3606 Version bump to 1.1.7

ac44c8968 updated form element test cases
