////
PLEASE AVOID UPDATES TO THIS PAGE

TODO: This content should be reorganized and moved to reference
////

[discrete]
==== Business Process Configuration
include::processConfiguration/BPMConfiguration.adoc[]

[discrete]
==== Function Handlers
**Function Handlers** are an abstraction within the framework to execute a common set of instructions for a given **Action**.

Given an action, a particular function handler can be executed by specifying a value for the query parameter **fn**.

.Example configuration for a _set function handler
[source,java]
----
@Config(url="/p/patient:<!/.m/id!>/_process?fn=_set")
----

In the example above, **_process_** is the **Action** and **_set_** is the Function Handler we have configured to execute as a part of this **@Config** configuration.

[discrete]
==== Predefined Function Handlers

There are several default function handlers defined within the core framework to handle common framework instructions, such as setting the state of a parameter (**_set_**) or adding a parameter value into a collection (**_add_**).

The following function handlers are provided out-of-the-box:

.Predefined Function Handlers
[options="header", cols="1, 1, 4"]
|=========================================================
| Handler 			| Action		| Description

| _param			| _get			|
| _default			| _nav			|
| _initEntity		| _new			|
| _add				| _process		| Adds parameter value to a collection.
| _addCollection	| _process		|
| _bpm				| _process		| Invokes a statless bpm process.
| _eval				| _process		|
| _set				| _process		| Sets parameter value.
| _setByRule		| _process		| Set parameter value through a rule.
| _example			| _search		|
| _lookup			| _search		|
| _query			| _search		|

|=========================================================

[discrete]
==== Custom Function Handlers

The framework provides the ability to users to define custom function handlers.

To create a custom function handler, create a **@Bean** to be injected in the spring context which implements **FunctionHandler** class from the framework.
Below are two samples for creating custom handlers.


[source,java,indent=0]
[subs="verbatim,attributes"]
.PetClinicExtensionConfig.java

@Configuration
public class PetClinicExtensionConfig {
	@Bean(name="default._process$execute?fn=_custom")
	public CustomFunctionHandler<?,?> setCustomFunctionHandler(BeanResolverStrategy beanResolver) {
		return new CustomFunctionHandler<>(beanResolver);
	}
	@Bean(name="petclinic._process$execute?fn=_setByRule")
	public SetByRuleFunctionHandler<?,?> setByRuleFunctionHandler() {
		return new SetByRuleFunctionHandler<>();
	}
}

Custom implementation example:


[source,java,indent=0]
[subs="verbatim,attributes"]
.CustomFunctionHandler.java
----
public class CustomFunctionHandler<T,S> implements FunctionHandler<T,S> {
	public CustomFunctionHandler(BeanResolverStrategy beanResolver) {}
	@Override
	public S execute(ExecutionContext eCtx, Param<T> actionParameter) {
		/**
		 * Add custom function handler logic here
		 **/
		return null;
	}
}
----
Usage: **@Config(url="/vpOwners/vtOwners/vsSearchOwnerCriteria/vfSearchOwnerCriteria/vbgSearchOwner/\_process?fn=\_custom")**

.Notes
* Naming convention for the bean name should to be followed for the custom function handler to be recognized by the framework - **<default>.\_process$execute?fn**
* <default> is used for the default implementation of framework.
It can be overwritten by specific implementations of the function handler by replacing <default> with ex. petclinic

include::processConfiguration/Querydsl.adoc[]
