[[param-pathing]]
= Param Path

As previously explained, every Java variable created under a domain entity definition will eventually result in the creation of a _param_. Each param that is created in this way has a unique *path* by which it can be identified through using the framework's Command Query DSL.

== Introduction
The path is represented as a URI address that uniquely identifies a param's location within the Framework. It is built by traversing through a Java class's members, with a `/` denoting a child member (child members are also often referred to as "nested" members).

An example of some param paths can be found in the sample code below:

[source, java]
----
@Domain("petshop")
@Repo
@Domain(value="petshop", includeListeners = { ListenerType.persistence })
@Repo(alias = "petshop", Database.rep_mongodb)
@Getter @Setter
public class PetShop {

    // Param Path: /petshop:1/name
    private String name;

    // Param Path: /petshop:1/address
    private Address address;

    // Param Path: /petshop:1/boardedPets
    private List<Pet> boardedPets;

    // Collection elements are also retrievable by supplying an index
    // immediately following member name.
    // Collection Element Param Path with index 0: 
    //   /petshop:1/boardedPets/0
    // Collection Element Param Path with index 1:
    //   /petshop:1/boardedPets/1
    // Collection Element Param Path with index n (where n is an 
    // integer >= 0): 
    //   /petshop:1/boardedPets/n

    @Model
    @Getter @Setter
    public static class Address {

        // /petshop:1/address/street
        private String street;

        ...
    }

    @Model
    @Getter @Setter
    public static class Pet {

        // /petshop:1/boardedPets/0/name
        // /petshop:1/boardedPets/1/name
        // /petshop:1/boardedPets/.../name
        private String name;

        ...
    }
}
----

Please note that in the example above all of the provided param paths are of the form: `/*petshop:1*/...`. The index `1` is known as a <<param-pathing-ref-id>>, which will be explained in the following section.

[[param-pathing-ref-id]]
== RefId
A _refId_ is a unique identifier used to identify a particular instance of _domain entity_ that has been created.

When a domain entity is configured with <<core-config-annotation-repo, `@Repo`>>, the _refId_ would be equivalent to the persistence ID used to store the object in the configured database.

=== Using the refId
The _refId_ is typically created and maintained by the Nimbus framework. It is often used in pathing or Nimbus DSL statements to retrieve data specific to a persisted entity.

_refId_ is configurable in the param path string with the syntax: `"\{DOMAIN_ALIAS\}:\{REF_ID\}"`. (e.g. `/petshop:1` or `/petshop:2`)

=== Relative param paths
While params may be resolved from the root param, it is not uncommon for params to be resolved relative to another param. The relative param is commonly referred to as a _context param_. This simply means that the path to the resolving param is simply relative from the path of the _context param_. This is achieved in the framework by using the familiar unix-style pathing syntax. For example, consider the following configuration:

[source,java]
----
@Model
@Getter @Setter
public static class SectionA {

    private String p1; <1>

    private Subsection1 subsection1;

    @Model
    @Getter @Setter
    public static class Subsection1 {

        private String p2; <2>
    }
}
----
<1> Assume the full path for this param is: `"/some_domain/page/view/tile/sectionA/p1"`
<2> Assume the full path for this param is: `"/some_domain/page/view/tile/sectionA/subsection1/p2"`

Using relative pathing, the following examples demonstrate relativity from one param to another:

* `p2` is relative to `p1` by the path: `"/../subsection1/p2"`
* `p1` is relative to `p2` by the path: `"/../../p1"`

== Cross Domain Pathing 
Sometimes it may be necessary to change the domain entirely to retrieve the data needed when working with param paths. This is achievable through the use of the param path marker `/p`. Simply start a param path with `/p` and the root domain context will be changed.

See <<param-pathing-reserved-keywords>> for more details on `/p`.

[[param-pathing-variable-resolver]]
== Path Variable Resolver

The Command Query DSL offers certain reserved variables or keywords that can be used in a path. The Framework uses a default implementation of `CommandPathVariableResolver` to resolve a param path from a provided from the context of another param.

=== Property Placeholders

The default implementation of `CommandPathVariableResolver` will attempt to first resolve `${...}` placeholders in the given path, replacing them with corresponding property values. Unresolvable placeholders without default value having been set is not supported.

[[param-pathing-reserved-keywords]]
=== Reserved Keywords
After resolving property placeholders reserved framework keywords will be resolved. The framework provides support for the following reserved keywords:

[cols="2, 14"]
|===
| Keyword | Description

| `/p` | The param path marker that denotes the start of a param path. This is only needed to be given when using a full URL or switching param contexts and is only recognized when used as the *start* of the param path.
| `/.m` | Resolves to the path of the param that is mapped to the param identified by the preceeding path. (e.g. `PARAM_PATH/.m` returns the mapped param of the param identified by `PARAM_PATH`.
| `/.d` | Resolves to the path of the param that is the root domain of the param identified by the preceeding path. (e.g. `PARAM_PATH/.d` returns the domain param that owns the param identified by `PARAM_PATH`.
| `<!#elemId!>` | Resolves to the _elemId_ of the command param, provided it is a _collection element param_. Works for _mapped params_ as well.
| `<!#env!>` | Uses the Spring `Environment` to resolve the preceeding path property. (e.g. `<!#env.spring.application.name!>` resolves using `Environment.getProperty("spring.application.name")`)
| `<!#refId!>` | Resolves to the <<param-pathing-ref-id>> of the `ExecutionContext` from which the command is being executed.
| `<!#self!>` | When preceeded with `loginId` or `id`, resolves to the respective field from the current logged in user's `ClientUser` object. Otherwise, resolves to the current <<command-dsl-client-alias>>.
| `<!#this!>` | Resolves to the path of the param in the current context.
|===