[[view-config-annotation-grid]]
= Grid

Grid is a table container capable of displaying tabular data.

.Allowed Parent Components
<<view-config-annotation-form>>, 
<<view-config-annotation-section>>

.Allowed Children Components
`@Grid` should decorate a field having a collection/array with a defined type. The defined type is treated as the definition for the row data in the rendered HTML table. This is referred to as the _collection element type_. The allowed children components of the collection element's type are:

<<view-config-annotation-grid-column>>, 
<<view-config-annotation-link-menu>>, 
<<view-config-annotation-grid-row-body>>

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@Grid
private List<PetLineItem> vgPets;

@Model
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    private String field1;

    @LinkMenu
    private VLMMain vlmMain;

    @GridRowBody
    private ExpandedRowContent expandedRowContent;

    @Model
    @Getter @Setter
    public static class VLMMain { ... }

    @Model
    @Getter @Setter
    public static class ExpandedRowContent { ... }
}
----

.Handling Multiple Row Selection in @Grid
Grid offers the ability to select multiple rows of data and submit the indexes of the selected rows to the server for processing.

In the example below, we can see an example of configuring a grid that should allow the user to select multiple 
rows and then perform some action with those selections.

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Grid(onLoad = true,
        rowSelection = true,
        postButtonUrl = "/view/page/tile/section/actionRemove",
        postButton = true,
        postButtonTargetPath = "temp_ids",
        postButtonAlias = "Remove")
@Path("/members")
@Config(url = "/p/member/_search?fn=example")
private List<VGGroupView> vgGroupList;

@Config(url = "/page/tile/section/tempIdsWrapper/_replace")
@Config(url = "/p/member:<!col!>/_delete", col = "<!/tempIdsWrapper/temp_ids!>"
private String actionRemove;

private TempIdsWrapper tempIdsWrapper;

@Model
@Getter @Setter
public static class TempIdsWrapper {
	private List<String> temp_ids;
}
----

// TODO - Write an explanation for the black magic that is coded above.

[[view-config-annotation-grid-column]]
== GridColumn

GridColumn is a container for displaying a single value within a <<view-config-annotation-grid>>.

.Allowed Parent Components
<<view-config-annotation-grid>>

.Allowed Children Components
None. `@GridColumn` should decorate a field having a simple type.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@Model
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    private String field1;
}
----

[[view-config-annotation-grid-row-body]]
== GridRowBody

GridRowBody is used to display additional content about the row data within a <<view-config-annotation-grid>>.

.Allowed Parent Components
<<view-config-annotation-grid>>

.Allowed Children Components
`@GridRowBody` will display children components in the same manner as <<view-config-annotation-section>> does. See the _Allowed Children Components_ of <<view-config-annotation-section>> for more details.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@MapsTo.Type(Pet.class)
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    @Path
    private String name;

    @GridRowBody
    private ExpandedRowContent expandedRowContent;

    @Model
    @Getter @Setter
	public static class ExpandedRowContent {
		
		@CardDetail
		private CardDetails cardDetails;
	}
	
	@Model
    @Getter @Setter
	public static class CardDetails {
		
		@CardDetail.Body
		private CardBody cardBody;
	}
	
	@Model
    @Getter @Setter
	public static class CardBody {
		
		@FieldValue
        @Path
		private String id;
	}
}
----
