[[view-config-annotation-grid]]
= Grid

Grid is a table container capable of displaying tabular data.

.Allowed Parent Components
<<view-config-annotation-form>>, 
<<view-config-annotation-section>>

.Allowed Children Components
`@Grid` should decorate a field having a collection/array with a defined type. The defined type is treated as the definition for the row data in the rendered HTML table. This is referred to as the _collection element type_. The allowed children components of the collection element's type are:

<<view-config-annotation-grid-column>>, 
<<view-config-annotation-link-menu>>, 
<<view-config-annotation-grid-row-body>>

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@Grid
private List<PetLineItem> vgPets;

@Model
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    private String field1;

    @LinkMenu
    private VLMMain vlmMain;

    @GridRowBody
    private ExpandedRowContent expandedRowContent;

    @Model
    @Getter @Setter
    public static class VLMMain { ... }

    @Model
    @Getter @Setter
    public static class ExpandedRowContent { ... }
}
----

.Handling Multiple Row Selection in @Grid
Grid offers the ability to select multiple rows of data and submit the indexes of the selected rows to the server for processing.

In the example below, we can see an example of configuring a grid that should allow the user to select multiple 
rows and then perform some action with those selections.
Setting `rowSelection` attribute to true will render a checkbox at the beginning of each row in the table for row selection and setting `postButton` to true, a button with name `postButtonAlias` is rendered on UI below the Grid. A wrapper class with List of Strings holds the elemIds (index of each row) of the rows that are selected. The variable name of the List<String> is provided in `postButtonTargetPath`. On click of the button, the `@Config` or `@Configs` decorated on the path provided in `postButtonUrl` are executed. 

In the below example, in a grid with 10 rows, if a user selects row # 2,4 & 8 and click on action button (Remove) - below actions happen in the same order

@Configs on `postButtonUrl` value are executed  (/view/page/tile/section/actionRemove) 
So first, @Config(url = "/page/tile/section/tempIdsWrapper/_replace") - this sets the value of the `temp_ids` with the array of Strings of row index values. i.e ["1", "3", "7"] (since index starts at 0)

Next, @Config(url = "/p/member:<!/../vgGroupList/<!col!>/id!>/_delete", col = "<!/tempIdsWrapper/temp_ids!>"), this uses the core config notation of looping through a list `col = "<!/tempIdsWrapper/temp_ids!>"` , which in this case is a list of elemIds(row index) and for each of the value - deletes the member record.

Note :: The position and style of the action button is static and cannot be configured. 

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Grid(onLoad = true,
        rowSelection = true,
        postButtonUrl = "/view/page/tile/section/actionRemove",
        postButton = true,
        postButtonTargetPath = "temp_ids",
        postButtonAlias = "Remove")
@Path("/members")
@Config(url = "/p/member/_search?fn=example")
private List<VGGroupView> vgGroupList;

@Config(url = "/page/tile/section/tempIdsWrapper/_replace")
@Config(url = "/p/member:<!/../vgGroupList/<!col!>/id!>/_delete", col = "<!/tempIdsWrapper/temp_ids!>")
private String actionRemove;

private TempIdsWrapper tempIdsWrapper;

@Model
@Getter @Setter
public static class TempIdsWrapper {
	private List<String> temp_ids;
}
----


[[view-config-annotation-grid-column]]
== GridColumn

GridColumn is a container for displaying a single value within a <<view-config-annotation-grid>>.

.Allowed Parent Components
<<view-config-annotation-grid>>

.Allowed Children Components
None. `@GridColumn` should decorate a field having a simple type.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@Model
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    private String field1;
}
----

[[view-config-annotation-grid-row-body]]
== GridRowBody

GridRowBody is used to display additional content about the row data within a <<view-config-annotation-grid>>.

.Allowed Parent Components
<<view-config-annotation-grid>>

.Allowed Children Components
`@GridRowBody` will display children components in the same manner as <<view-config-annotation-section>> does. See the _Allowed Children Components_ of <<view-config-annotation-section>> for more details.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Sample Configuration
----
@MapsTo.Type(Pet.class)
@Getter @Setter
public static class PetLineItem {

    @GridColumn
    @Path
    private String name;

    @GridRowBody
    private ExpandedRowContent expandedRowContent;

    @Model
    @Getter @Setter
	public static class ExpandedRowContent {
		
		@CardDetail
		private CardDetails cardDetails;
	}
	
	@Model
    @Getter @Setter
	public static class CardDetails {
		
		@CardDetail.Body
		private CardBody cardBody;
	}
	
	@Model
    @Getter @Setter
	public static class CardBody {
		
		@FieldValue
        @Path
		private String id;
	}
}
----
