[[command-dsl-sending-a-payload]]
= Sending a payload with a Command
The `rawPayload` attribute of `Command` is used in several different client facing implementations to input data into Nimbus for processing. Primarily used as an argument, it is a unversal o

[[rawpayload-as-query-param]]
== Send rawPayload as a query parameter
Simply provide `rawPayload` as a query parameter with a JSON string value representing the desired value to provide within the <<command-dsl, command query>> statement.

[[rawpayload-as-payload]]
== Send rawPayload as HTTP Payload content
The `WebActionController` offers native payload support for some HTTP operations such as `POST` or `PUT`. One such example can be seen with the following button implementation

[source, java]
----
@Form
private VFForm vfForm;

@MapsTo.Type(Person.class)
@Getter @Setter
public static class VFForm {

    @Label("Search Term")
    @TextBox
    @Path("/firstName")
    private String searchTerm;

    @Button(type = Button.Type.submit) <1>
    @Config(url = "<!#this!>/../_replace") <2>
    private String submit;
}
----
<1> On click of this button on the UI, the browser will send an HTTP `POST` with a JSON payload representing the form data. The `WebActionController` knows to convert this data into the `rawPayload`, which can then be forwarded on to subsequent commands.
<2> The command generated by this query will have it's `rawPayload` set and consequently will use the <<command-dsl-actions-replace>> behavior to set the state of `vfForm` to it.

[NOTE]
The submit button behavior occurs since the default UI behavior for `Button.Type.submit` will post it's parent's encapsulated form data.

See the `WebActionController` implementation for more details.

== Priority of how rawPayload is set
The priority of how `rawPayload` is used in the search by example handler is:

. Query param
. HTTP payload
