[[config-annotations-activate-conditional]]
= ActivateConditional

`@ActivateConditional` is an extension capability provided by the framework. The annotation is used to conditionally activate/deactivate the param based on a SpEL condition.

To dectivate a param means to mark the param the `enabled` and `visible` properties as well as nullify the state of the target param.

TIP: It is common to misuse `@ActivateConditional` when `<<config-annotations-enable-conditional, @EnableConditional>>` or `<<config-annotations-enable-conditional, @EnableConditional>>` would be a better choice. While this annotation is similar to using `<<config-annotations-enable-conditional, @EnableConditional>>` and/or `<<config-annotations-visible-conditional, @VisibleConditional>>`, it should be noted that `@ActivateConditional` nullify the state of the target param.

The logic for `@ActivateConditional` can be found in `ActivateConditionalStateEventHandler`. The handler logic will be executed during the following framework events: 

* OnStateLoad
* OnStateChange

[source,java,indent=0]
[subs="verbatim,attributes"]
.ActivateConditional.java
----
@CheckBox(postEventOnChange=true)
@ActivateConditional(when="state != 'true'", targetPath="/../sectionG_skip")
private String skipSectionG;

private sectionG_Skip sectionG_skip;

@Radio(postEventOnChange=true)
@Model.Param.Values(value=YNType.class)
@ActivateConditional(when="state == 'No'", targetPath="/../q3Level2")
private String answerYesOrNo;

private Q3 q3Level2;

@CheckBoxGroup(postEventOnChange=true)
@Model.Param.Values(value=Days.class)
@ActivateConditional(when="state == new String[]{'Sunday'}",targetPath="/../../../sundayDeliverySection")
private String[] deliveryDays;

/*Check if selection contains one or more specific values*/
@CheckBoxGroup(postEventOnChange=true)
@Model.Param.Values(value=Days.class)
@ActivateConditional(when="state != null && state.?[#this=='Sunday'] != new String[]{}",targetPath="/../../../sundayDeliverySection")
private String[] deliveryDays;

@CheckBoxGroup(postEventOnChange=true)
@Model.Param.Values(value=VisitCount.class)
@ActivateConditional(when="state != null && state.length > 2",targetPath="/../../section")
private String[] visits;
----
