[[command-dsl-actions-update]]
= Update

The action __update sets individual fields of the state of the param identified by _domain alias_ to the fields within the object provided as a query parameter: _rawPayload_. When using the update action, not providing explicit values for fields will result in any existing state within the identified param to be preserved. In a situation where only the state needs to be explicitly set, consider using <<command-dsl-actions-replace>>.

== Examples
The following class will be used in the __update_ scenarios to follow.

[source, java]
----
@Domain("sample_entity")
@Getter @Setter
public class SampleEntity {

    private String single_element;

    private List<String> collection;
}
----

The following scenarios will also assume that the param at _sample_entity:1_ has a pre-existing state of:
[source,json]
----
{
    "single_element": "empty_value",
    "collection": ["empty_value_1"]
}
----

---

[discrete]
=== Updating a single element state
`@Config(url = "sample_entity:1/single_element/_update?rawPayload='hello'")`

.Resulting State of _sample_entity:1_
[source,json]
----
{
    "single_element": "hello",
    "collection": ["empty_value_1"]
}
----

As the path in this scenario is pointing to `sample_entity:1/single_element`, only the field `single_element` is subject to be updated with the value of `rawPayload`. The value for the field of `collection` is unaffected and retains it's previous value.

---

[discrete]
=== Updating a collection element state
`@Config(url = "sample_entity:1/collection/0/_update?rawPayload='hello'")`

.Resulting State of _sample_entity:1_
[source,json]
----
{
    "single_element": "empty_value",
    "collection": ["hello"]
}
----

As the path in this scenario is pointing to `sample_entity:1/collection/0`, only the collection element at index `0` for the field `collection` is subject to be updated with the value of `rawPayload`. The value for the field of `single_element` is unaffected and retains it's previous value.

---

[discrete]
=== Updating a collection state
`@Config(url = "sample_entity:1/collection/_update?rawPayload='\"new_value\"'")`

.Resulting State of _sample_entity:1_
[source,json]
----
{
    "single_element": "empty_value",
    "collection": ["empty_value_1", "new_value"]
}
----

As the path in this scenario is pointing to `sample_entity:1/collection`, only the field `collection` is subject to be updated with the value of `rawPayload`. Performing an __update_ call on a collection essentially performs an *add* operation. The value for the field of `single_element` is unaffected and retains it's previous value.

TIP: If needing to replace elements within the collection as a whole, consider using <<command-dsl-actions-replace>>.

It is also permissible to pass an array as a payload. 

`@Config(url = "sample_entity:1/collection/_update?rawPayload='[\"new_value_1\", \"new_value_2\"]'")`

.Resulting State of _sample_entity:1_
[source,json]
----
{
    "single_element": "empty_value",
    "collection": ["empty_value_1", "new_value_1", "new_value_2"]
}
----

In this scenario, *all of the array elements* within `rawPayload` would be added to the collection.

---

[discrete]
=== Updating a complex object
`@Config(url = "sample_entity:1/_update?rawPayload='{\"single_element\": \"hello\"}'")`

.Resulting State of _sample_entity:1_
[source,json]
----
{
    "single_element": "hello",
    "collection": ["empty_value_1"]
}
----

As the path in this scenario is pointing to `sample_entity:1`, both fields are subject to be updated with the value of `rawPayload`. Performing an __update_ call in this call preserves any previously existing state for fields not specified in the `rawPayload`. Consequently, the value for the field of `single_element` is updated, while `collection` is unaffected and retains it's previous value.

TIP: Nested domain models can become quite large! Use __update_ when needing to target specific values within a domain entity.

---

[discrete]
=== Updating an entity state with the value of another entity state
`@Config(url = "sample_entity:1/single_element/_update?rawPayload=<!json(PATH_TO_PARAM)!>)`

where `PATH_TO_PARAM` is path which points to another param, relative to the location of `single_element`.

As the path in this scenario is pointing to `sample_entity:1/single_element`, only the field `single_element` is subject to be updated with the value of `rawPayload`. The value to be set will be the same as the state of the object identified by `PATH_TO_PARAM`.

TIP: This scenario can be used to copy a param's state from one param to another.

---

[discrete]
=== Updating an entity state with post data
`@Config(url = "sample_entity:1/single_element/_update")`

.Post Data
"hello"

.Resulting State of _sample_entity:1_
[source,json]
----
{
    "single_element": "hello",
    "collection": ["empty_value_1"]
}
----

As the path in this scenario is pointing to `sample_entity:1/single_element`, only the field `single_element` is subject to be updated with the HTTP post data. The value for the field of `collection` is unaffected and retains it's previous value.