This section covers the _conditional behavior_ that can be applied to params. In this context, _conditional behavior_ refers to 
performing a set of actions based on a given condition. The condition is evaluated by using the powerful capabilities of _SpEL 
(Spring Expression Language)_. 

Typically this _conditional behavior_ is evaluated from the context of the _conditionally decorated param_ (the param that is annotated 
with a conditional annotation), meaning that the condition will inspect the _decorated param_ object to infer if the condition 
should be `true` or `false`.

The following example shows what a conditional configuration might look like:

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@SampleConditional(when = "state == 'YES'")
@Radio(postEventOnChange = true)
@Values(YesNo.class)
private String question;
----

The `when` condition is effectively stating, when `question.getState().equals("YES")`. In this case, since `question` is the _decorated 
param_, we are evaluating from the context of `question`. This is why `state` is understood in the _SpEL_ condition `state == 'YES'`. 

NOTE: In this scenario `@SampleConditional` is not a real annotation understood by the framework, but it illustrates the idea that when 
this particular _condition_ is `true`, we should perform some sort of behavior. We defer that logic to _State Event Handlers_.

[discrete]
==== State Event Handlers
The role of a _State Event Handler_ is to instruct the framework on how to process a conditional annotation. Therefore, it is responsible 
for maintaining the logic to be applied when a conditional annotation is present on a param. _State Event Handlers_ are registered with 
the framework through the use of `@EventHandler` on startup as Spring beans. The logic is then executed during specific event hooks 
defined within the framework.

// TODO: Link to the available events.

[discrete]
==== Framework Defined Conditional Annotations

[discrete]
===== AccessConditional
include::conditionals/accessConditional.adoc[]

[discrete]
===== AccessConditionals
include::conditionals/accessConditionals.adoc[]

[discrete]
===== ActivateConditional
include::conditionals/activateConditionals.adoc[]

[discrete]
===== ActivateConditionals
include::conditionals/activateConditionals.adoc[]

[discrete]
===== ConfigConditional
include::conditionals/configConditional.adoc[]

[discrete]
===== EnableConditional
include::conditionals/enableConditional.adoc[]

[discrete]
===== EnableConditionals
include::conditionals/enableConditionals.adoc[]

[discrete]
===== ValidateConditional
include::conditionals/validateConditional.adoc[]

[discrete]
===== ValidateConditionals
include::conditionals/validateConditionals.adoc[]

[discrete]
===== ValuesConditional
include::conditionals/valuesConditional.adoc[]

[discrete]
===== ValuesConditionals
include::conditionals/valuesConditionals.adoc[]
