
[discrete]
==== AccessConditional
@AccessConditional allows to control the access of the specific area/functionality within the application based on User's assigned role(s) and permission(s).

Example:

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@AccessConditional(whenAuthorities="?[#this == 'entity_assign'].empty", p=Permission.HIDDEN)
private Section_EntityAssignment vsEntityAssignment;
----
Above configuration would hide the entity assignment section for user(s) who do not have access to "entity_assign" action.

.AccessConditional Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
| Name 			| Type			 | Default			 | Description

| whenAuthorities			| String		 | 					 | SpEL (spring expression language) to check for user permissions **Recommended**
| whenRoles			| String		 | 					 | SpEL (spring expression language) to check for user roles
| containsAuthorites			| String[]		 | 					 | Simple contains check for user permissions. (for more complex conditions, use _whenAuthorities_)
| containsRoles			| String[]		 | 					 | Simple contains check for user roles. (for more complex conditions, use _whenRoles_)
|=========================================================

CAUTION: **_whenRoles_** and **_containsRoles_** should be used with caution, since roles may be added/changed more frequently in the application and in that event, you would need to update the entity configurations.

More Examples:

[source,java,indent=0]
[subs="verbatim,attributes"]
----
// vbEntityCreate will be hidden for user(s) who do not have access to "entity_create"
@AccessConditional(whenAuthorities="?[#this == 'entity_create'].empty", p=Permission.HIDDEN)
private Button_EntityCreate vbEntityCreate;

//vsEntityEdit will be hidden for user(s) who do not have access to "entity_create" or "entity_edit"
@AccessConditional(whenAuthorities="?[#this == 'entity_create'].empty && ?[#this == 'entity_edit'].empty", p=Permission.READ)
private Section_EntityEdit vsEntityEdit;
----

[discrete]
==== AccessConditionals
@AccessConditionals is a collection of AccessConditional calls.

.AccessConditionals Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |AccessConditional[] |  |

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.AccessConditionals.java
----
	@AccessConditionals({
		@AccessConditional(whenAuthorities="!?[#this == 'entity_management'].empty || !?[#this == 'entity_create'].empty", p=Permission.READ)
		@AccessConditional(whenAuthorities="?[#this == 'entity_management'].empty && ?[#this == 'entity_create'].empty", p=Permission.HIDDEN)
	})
	private String entity_accessConditionals;
----

[discrete]
==== ActivateConditional

Activate Conditional is an extension capability provided by the framework. The annotation is used to conditionally activate/deactivate the param based on a SpEL condition.
This annotation can be triggered for multiple events. Framework provides default event handling for this annotation on StateChange and StateLoad.

.ActivateConditional Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|when |String | |SpEL based condition to be evaluated relative to param's state on which this annotation is declared.
|targetPath|String[] | | Path of param to activate when condition is satisfied relative to param on which this annotation is declared. Multiple target paths can be given
|inactivateWhen|String | emptyString|SpEL based condition on which param would be inactivated.If value is not overridden, then the negation of ActivateConditional#when() would be used
|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.ActivateConditional.java
----
@CheckBox(postEventOnChange=true)
@ActivateConditional(when="state != 'true'", targetPath="/../sectionG_skip")
private String skipSectionG;

private sectionG_Skip sectionG_skip;

@Radio(postEventOnChange=true)
@Model.Param.Values(value=YNType.class)
@ActivateConditional(when="state == 'No'", targetPath="/../q3Level2")
private String answerYesOrNo;

private Q3 q3Level2;

@CheckBoxGroup(postEventOnChange=true)
@Model.Param.Values(value=Days.class)
@ActivateConditional(when="state == new String[]{'Sunday'}",targetPath="/../../../sundayDeliverySection")
private String[] deliveryDays;

/*Check if selection contains one or more specific values*/
@CheckBoxGroup(postEventOnChange=true)
@Model.Param.Values(value=Days.class)
@ActivateConditional(when="state != null && state.?[#this=='Sunday'] != new String[]{}",targetPath="/../../../sundayDeliverySection")
private String[] deliveryDays;

@CheckBoxGroup(postEventOnChange=true)
@Model.Param.Values(value=VisitCount.class)
@ActivateConditional(when="state != null && state.length > 2",targetPath="/../../section")
private String[] visits;
----
Example SpEL expressions:

[source,java,indent=0]
[subs="verbatim,attributes"]
//Contains single element:
@ActivateConditional(when="state != null && state.?[#this=='Apple'] != new String[]{}", targetPath = {"/../xyz","/../abc"})
//Contains exactly one single element:
@ActivateConditional(when="state == new String[]{'Apple'}", targetPath = {"/../xyz","/../abc"})
//Evaluate multiple or conditions
@ActivateConditional(when="state!=null && state.?[#this=='Apple' || #this=='Google'] != new String[]{}",targetPath="/../")

[discrete]
==== ActivateConditionals
@ActivateConditionals is a collection of ActivateConditional calls.

.ActivateConditionals Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |ActivateConditional[] |  |

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.ActivateConditionals.java
----
	@ActivateConditionals({
		@ActivateConditional(when="state == 'A'", targetPath="/../q3Level1"),
		@ActivateConditional(when="state == 'B'", targetPath="/../q3Level2")
	})
	private String q3;
	private SampleCoreNestedEntity q3Level1;
	private SampleCoreNestedEntity q3Level2;
----

[discrete]
==== Config

.Config Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|url |String |  |

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Config.java
----
@Config(url="/pageAddEditGoal/tileEditGoal/sectionEditGoal/goalDetailsForm/_nav?pageId=pageCarePlanSummary")
@Button(type = Button.Type.PLAIN)
private String cancel;
----

A class with @Config annotation is used to perform an action on button click.
In most cases, the action is to retrieve values via HTTP Rest calls
from database (MongoDB), and display on the web page. +

In the example shown above, when the button is clicked, the control will be navigated to the specified url. +
_nav_ is the http call for navigation. +

The possible Actions are: - +

 - get for HTTP GET
 - new for HTTP post
 - update for HTTP update
 - delete for HTTP delete
 - search for searching
 - nav for navigation
 - process for custom process/ work-flow definitions

[discrete]
===== Configs

.Configs Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|values |Config[] |  |

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Configs.java
----
@Configs({
@Config(url="~/client/org_name/_update"),
@Config(url="~/client/org_name/_process?fn=_set&url=/p/cmcase/_search?fn=query&where=cmcase.patientReferred.firstName.eq('<!/.m/patientReferred/firstName!>').and(cmcase.patientReferred.lastName.eq('<!/.m/patientReferred/lastName!>'))"),
@Config(url="~/client/org_name/_nav?pageId=vpAdvancedCaseSearch")
		})
@Button(type=Button.Type.PRIMARY, formReset=false)
private String submit;
----

@Configs is a collection of configuration calls. Multiple calls to the database
can be made simultaneously using @Configs, where each call will be represented by @Config. +

As shown in the example, when the submit button is clicked, three http calls that are being made viz.
update, process, and navigation.

[discrete]
==== ConfigConditional
ConfigConditional is an extension capability provided by the framework. The annotation is used to conditionally execute @Config calls based on a SPel based condition.
This annotation can be triggered for multiple events. Framework provides default event handling for this annotation on StateChange.

.ConfigConditional Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|when |String | |SpEL based condition to be evaluated relative to param's state on which this annotation is declared.
|config|Config[] | emptyString| Array of @Configs
|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.ConfigConditional.java
----
@ConfigConditional(
	when = "state == 'Completed'", config = {
	@Config(url="<!#this!>/../state/_update?rawpayload=\"Closed\""),
	@Config(url="/p/dashboard/_get")
})
private String status;
----
NOTE: In the above example , whenever there is statechange of status and the status is changed to *Completed*, the Configs will be executed.

[discrete]
==== ConfigNature

[discrete]
===== Ignore

Framework persists the data objects of a class in database using @Repo by serializing the class and associating a version number that is called seriaVersionUID.
However, if we do not want the framwework to serialize for time being, we can use @Ignore component of ConfigNature class. The following example shows that: -


[source,java,indent=0]
[subs="verbatim,attributes"]
.StartsWith.java
----
@Domain(value="patient", includeListeners={ListenerType.persistence})
@Repo(value=Database.rep_mongodb, cache=Cache.rep_device)
@ToString
public class Patient extends IdString {

	@Ignore
	private static final long serialVersionUID = 1L;

	}
----

[discrete]
==== Domain

Core Config configuration @Domain annotation persists data. +

Core config @Domain will always be followed by @Repo that will specify the way data is persisted. +

*includeListeners={ListenerType.persistence, ListenerType.update}* of @Domain
specifies that the data will be persisted. +
*value=Database.rep_mongodb* of @Repo specifies that a class with
@Domain annotation will use MongoDb for persistence.


[source,java,indent=0]
[subs="verbatim,attributes"]
.Domain.java
----
@Domain(value="cmcase", includeListeners={ListenerType.persistence, ListenerType.update})
@Repo(value=Database.rep_mongodb, cache=Cache.rep_device)
public class CMCase extends IdString {
}
----

NOTE: Please read @Repo for mroe information regarding @Repo annotation.

[discrete]
===== EnableConditional
EnableConditional is an extension capability provided by the framework. The annotation is used to conditionally activate/deactivate the param based on a SpEL condition. This annotation can be triggered for multiple events. Framework provides default event handling for this annotation on StateChange and StateLoad.
The difference between this annotation and @ActivateConditional is this annotation only affects the "enabled" state whereas @ActivateConditional affects both "enabled" and "visible" state.

.EnableConditional Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|when |String | |SpEL based condition to be evaluated relative to param's state on which this annotation is declared.
|targetPath|String[] | | Path of param to enable when condition is satisfied relative to param on which this annotation is declared
|disableWhen |String | | SpEL based condition on which param would be disabled. If value is not overridden, then the negation of EnableConditional#when() would be used
|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.EnableConditional.java
----
	@EnableConditional(when="state == 'hooli'", targetPath="../enable_p2")
	private String enable_p1;

	private String enable_p2;
----

[discrete]
==== EnableConditionals
@EnableConditionals is a collection of EnableConditional calls.

[discrete]
==== Execution
Execution is inherited annotation for @Config and @KeyValue. It is not currently being directly used, but is there for hieracrchial purposes.

More documentation will be added here if Execution expands or is directly used.

[discrete]
==== MapsTo

[discrete]
===== Path

.Path Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |String |  |specify value of Path
|colElemPath |String | DEFAULT_COL_ELEM_PATH | specifies column element path
|state |State | State.Internal | specifie path state
|linked |boolean |true | determine if the path has links
|cache |Cache | Cache.rep_device | specifies cache type

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Path.java
----
@Path()
private Long version;
----

[discrete]
===== Type

.Type Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |class<?> | |
|silent |boolean | true |determines if Type is silent

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Type.java
----
@MapsTo.Type(CMCase.class)
public static class SectionEditGoal  {
    }
----

NOTE: If it is not mapped _(@Mapped)_, an exception will be thrown. +
If no exception is thrown, defaults to silent.

[discrete]
==== Model

[discrete]
===== Param

.Param Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |Class<? extends Source> | Source.class |specify value of Path
|url |String | staticCodeValue | specifies url

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Param.java
----
@Model.Param.Values(url="~/client/orgname/staticCodeValue/_search?fn=lookup&where=staticCodeValue.paramCode.eq('/thisIsParentQuestion14')")
@Radio(postEventOnChange=true, controlId = "27")
private String thisIsParentQuestion14;
----

NOTE: The example will retrieve the value of Radio button from the specified url. +
*staticCodeValue* is a collection in MongoDB that will be searched and retrieved using @Model annotation.
The search criteria is specified using param code _thisIsParentQuestion14_

[discrete]
===== Text

.Text Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|label |String | |

|=========================================================

[discrete]
==== ParamContext

**@ParamContext** is used to set the contextual properties of a field during the _OnStateLoad_ event (e.g. _visible_, _enabled_).

.ParamContext Attributes
[cols="3, 3, 3, 10",options="header"]
|=========================================================
| Name 			| Type			| Default	 | Description

| visible		| boolean		| 			 | Whether or not the decorated target should be visible.
| enabled		| boolean		|			 | Whether or not the decorated target should be enabled.
|=========================================================

The intent of **@ParamContext** is to be able to decorate fields to define default contextual behavior. For example:

[source,java,indent=0]
[subs="verbatim,attributes"]
.SampleView.java
----
 public static class SampleView {

    @TextBox
    @ParamContext(enabled=false, visible=false)
    private String myTextBox;
 }
----

In this scenario we have configured the contextual values for _enabled_ and _visible_ to be **false** for _myTextBox_. These values will
be set during the _OnStateLoad_ event and _myTextBox_ consequently will not be enabled or visible when the corresponding page is rendered.

TIP: **@ParamContext** can also be defined on annotations. In these scenarios when a field is decorated with that annotation, then the
handler for **@ParamContext** will execute. This may be useful when building a framework extension.

[discrete]
==== SearchNature

[discrete]
===== StartsWith

This component is ued to validate a field. The wilcard attribute determines the validation criteria for a field. This is a server side component.

.StartsWith Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|wildCard |String | * |determines the search criteria

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.StartsWith.java
----
@NotNull
@StartsWith
@Label(value = "First Name")
private String firstName;
----

NOTE: The example will always search the first name that starts with anything, represented with the default value. A specific search criteria can be
specified using wildcard attribute of @StartsWith.

[discrete]
==== Repo

.Repo Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description
|alias |String | | cannot be changed
|value |enum |  |specify value of Path
|cache |enum | Cache.rep_device | specifies cache type
|autoSave |boolean |true | determine if the autosave is enabled

|=========================================================

NOTE: The possible enum values for value are *DATABASE.rep_none, DATABASE.rep_rdbms, DATABASE.rep_mongodb, DATABASE.rep_ws* +
The possible enum values for cache are *CACHE.rep_none, CACHE.rep_device*

@Repo is used to determine where the data will be persisted. It is always used along with @Domain. +

[discrete]
===== rep_mongodb

The following example shows how data is persisted/ retrieved using MongoDB as a source.


[source,java,indent=0]
[subs="verbatim,attributes"]
.Repo.java
----
@Domain(value="cmassessment", includeListeners={ListenerType.persistence})
@Repo(alias="cmassessment",value=Database.rep_mongodb, cache=Cache.rep_device)
@Getter @Setter
public class CMAssessment extends IdString {
}
----

[discrete]
===== rep_ws

Databse values can be persisted/ retrieved not only using internal MongoDb as a source, we can now use an external web service for the same purpose.
All we have to do is create a REST call to a web service that will provide or store the data. Following is an example: -


[source,java,indent=0]
[subs="verbatim,attributes"]
.ExtClient.java
----
@Domain(value="ext_client")
@Repo(value=Database.rep_ws, cache=Cache.rep_device)
@Getter @Setter @ToString(callSuper=true)
public class ExtClient {

}
----

Notice *@Repo(value=Database.rep_ws)* in the code above. This indicates that it will make use of an external web service call rather than
a MongoDb call for ExtClient data objects' persistence/ retrieval purposes.

The advantage of this feature is that now we do not rely on internal source only. This gives us better flexibility and maintainability

[discrete]
==== Rule

@Rule allows its decorated field a mechanism for triggering one or more rule definitions during its OnStateLoad and OnStateChange events.

[source,java,indent=0]
[subs="verbatim,attributes"]
.SampleRuleEntity.java
----
@Domain(value="sample_rule_entity", includeListeners={ListenerType.persistence})
@Repo(Database.rep_mongodb)
@Getter @Setter
public class SampleRuleEntity {

	// Execute the rule at "rules/sample_increment" during the OnStateLoad and
	// OnStateChange events of ruleParam.
	@Rule("rules/sample_increment")
	private String rule_param;
}
----

By default, the framework provides support for firing all rules for a given domain entity. That is, for the *SampleRuleEntity.java* above we might have a rule file defined as *sample_rule_entity.drl* which will be automatically fired by naming convention.

For cases where additional configuration for other rules is needed, @Rule can be used.

.Rule Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
| Name 			| Type			 | Default			 | Description

| value			| String[]		 | 					 | rule file path(s) to execute.
|=========================================================

[discrete]
==== ValidateConditional

The ValidateConditional annotation is used to conditionally set validations that should appear for a param based on a SpEL condition. This 
annotation can be triggered for multiple conditions, if necessary. 

The framework provides default event handling for this annotation on StateChange and StateLoad.

.ValidateConditional Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
| Name 			| Type			 					| Default					| Description

| scope			| ValidationScope					| ValidationScope.SIBLING	| The scope for the param layer at which validations will be applied
| targetGroup	| Class<? extends ValidationGroup>	|							| Specifies which validation group should be applied
| when			| String							| 							| Configures whether or not the first truthy condition should be exclusive. If true, then only the first truthy condition will be executed. If false then all truthy conditions will be executed. the default value is true.
|=========================================================

[discrete]
===== Configuring Conditional by Group
ValidateConditional works by first evaluating the _when_ attribute by means of a SpEL condition. When the _when_ condition is true, the 
framework will attempt to identify a subset of params with Validation constraints and apply validation logic to those params. See the 
following example:

[source,java,indent=0]
[subs="verbatim,attributes"]
.@ValidateConditional Sample #1
----
@ValidateConditional(when = "state == 'dog'", targetGroup = GROUP_1.class)
@TextBox(postEventOnChange = true)
private String petType;

@NotNull
@TextBox
private String petName;

@NotNull(groups = { GROUP_1.class })
@TextBox
private String dogFood;

@NotNull(groups = { GROUP_2.class })
@TextBox
private String catFood;
----

====
.@ValidateConditional Sample #1 - Results
In the above example, assuming the state of _petType_ is *"dog"*, the validations that will be applied are: _petName_ and _dogFood_.

* _petName_ - There are no groups associated with _petName_, hence it is seen as a _static validation_ and always applied.
* _dogFood_ - _GROUP_1.class_ is present within the _@NotNull_'s _groups_ attribute, and this is matching _petType_'s 
_@ValidateConditional_'s _targetGroup_ attribute(*GROUP_1.class*) and is applied.

The validations that will not be applied are: _catFood_.

* _catFood_ - While _catFood_ has an entry in _@NotNull_'s _groups_ attribute(*GROUP_2.class*), it is not matching _@ValidateConditional_'s 
_targetGroup_ attribute(*GROUP_1.class*).
====

[discrete]
===== Specifying a Validation Group
As seen in the previous example, there may be many params decorated with _javax.validation.constraints_, we need to uniquely identify which 
validations should be applied when the _when_ condition is *true*. To handle this, the framework makes use of the _groups_ attribute 
supplied by of all _javax.validation.constraints_ annotation classes. The final subset of params where validations will be applied will be 
composed of only those whos _groups_ attribute contains the _@ValidateConditional_ _targetGroup_ attribute.

_@ValidateConditional_'s _targetGroup_ parameter is simply a marker interface of type _ValidationGroup_ to be used for identification 
purposes by the framework to identify a subset of params in which @ValidateConditional should apply validations to.

[NOTE]
====
Use link:_validateconditionals[@ValidateConditionals] when:

* Different groups should be applied based on multiple _when_ conditions
* Multiple groups should be applied for the same _when_ condition
====

[discrete]
====== Validation Group Identity Classes
In the previous example, we used _targetGroup_=**GROUP_1.class**. **GROUP_1.class** is an identity class that implements the 
_ValidationGroup_ interface and is used by the framework to identify _javax.validation.constraints_ annotatons that should be applied. 

Any implementation that implements the _ValidationGroup_ interface may be used as a group identity class. For convenience, a set of 
identify class implementations have been defined within @ValidateConditional as __GROUP_**X**.class__, where 0 \<= *X* \<= 9.

[NOTE]
If additional marker classes are needed, simply create a new implementation of _ValidationGroup_ and use that class in the _targetGroup_ 
attribute as well as the corresponding param's _javax.validation.constraints_ annotation.

[discrete]
===== Controlling Scope
Given that the framework uses _groups_ to identify which params should have validations applied, it needs a way to also limit the number
of params that will be considered during the processing phase. For example, should a _@ValidateConditional_ trigger **all** defined params
in the application that have a particular _targetGroup_? While necessary, such an operation may be costly.

The framework has provided the ability to define a _ValidationScope_ as part of _@ValidateConditional_'s _scope_ to handle this scenario. 
The following scopes are available:

._@ValidateConditional_ Scopes
[cols="3, 10", options="header"]
|=========================================================
| Name 				| Description

| **SIBLING**			| Applies validations to sibling params relative to the current param on which this annotation is defined.
| **SIBLING_NESTED**	| Applies validations to sibling params relative to the current param on which this annotation is defined. 
						  Also recursively traverses each of the previous param's nested params (or children) and applies validations.				
|=========================================================

[discrete]
==== ValidateConditionals
@ValidateConditionals is a collection of ValidateConditional calls.

_@ValidateConditionals_ should be used when multiple _@ValidateConditional_ calls are needed to decorate a single param. See the following
example:

[source,java,indent=0]
[subs="verbatim,attributes"]
.@ValidateConditionals Sample #1
----
@ValidateConditionals({
	@ValidateConditional(when = "state == 'dog'", targetGroup = GROUP_1.class),
	@ValidateConditional(when = "state == 'cat'", targetGroup = GROUP_2.class)
})
@TextBox(postEventOnChange = true)
private String petType;

@NotNull
@TextBox
private String petName;

@NotNull(groups = { GROUP_1.class })
@TextBox
private String dogFood;

@NotNull(groups = { GROUP_2.class })
@TextBox
private String catFood;
----

====
.@ValidateConditionals Sample #1 - Results #1
The state of _petType_ is *"dog"*.

The validations that will be applied are: _petName_ and _dogFood_.

* _petName_ - There are no groups associated with _petName_, hence it is seen as a _static validation_ and always applied.
* _dogFood_ - _GROUP_1.class_ is present within the _@NotNull_'s _groups_ attribute, and this is matching _petType_'s 
_@ValidateConditional_'s _targetGroup_ attribute(*GROUP_1.class*) and is applied.

The validations that will not be applied are: _catFood_.

* _catFood_ - While _catFood_ has an entry in _@NotNull_'s _groups_ attribute(*GROUP_2.class*), it is not matching _@ValidateConditional_'s 
_targetGroup_ attribute(*GROUP_1.class*).


.@ValidateConditionals Sample #1 - Results #2
The state of _petType_ is *"cat"*.

The validations that will be applied are: _petName_ and _catFood_.

* _petName_ - There are no groups associated with _petName_, hence it is seen as a _static validation_ and always applied.
* _catFood_ - _GROUP_2.class_ is present within the _@NotNull_'s _groups_ attribute, and this is matching _petType_'s 
_@ValidateConditional_'s _targetGroup_ attribute(*GROUP_2.class*) and is applied.

The validations that will not be applied are: _dogFood_.

* _dogFood_ - While _catFood_ has an entry in _@NotNull_'s _groups_ attribute(*GROUP_1.class*), it is not matching _@ValidateConditional_'s 
_targetGroup_ attribute(*GROUP_2.class*).
====

[discrete]
==== Values
Values provides a mechanism for populating a fields _values_ property. This can be used by a number of components
to perform such functions as: define a set of selections for radio buttons and checkboxes, or populating a dropdown list.

.Values Attributes
[cols="3, 5, 3, 10",options="header"]
|=========================================================
| Name 			| Type			 				| Default			 | Description

| value			| Class<? extends Source>		| EMPTY				 | Source implementation that returns a list of **ParamValues**
| url			| String						|					 | url endpoint that returns a list of **ParamValues**
|=========================================================

NOTE: _value_'s default value is **EMPTY**, which is a simple Source implementation that returns an empty list of **ParamValues**.

[discrete]
===== Source
The Source is a simple abstraction for providing a contract between implementations to provide data to the framework.

Source is exclusively used for **@Values**.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Source.java
----
public static interface Source {
	public List<ParamValue> getValues(String paramCode);
}
----

We can use this to define several different types of values providers. A simple static Source implementation is shown below:

[source,java,indent=0]
[subs="verbatim,attributes"]
.SampleStaticSource.java
----
public class SampleStaticSource implements Source {
	public List<ParamValue> getValues(String paramCode) {
		List<ParamValue> values = new ArrayList();
		values.add(new ParamValue("sample.value.1", "Sample Value 1"));
		return values;
	}
}
----

[discrete]
===== Examples

.Using a static Source implementation to define a set of values
[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Values(SampleStaticSource.class)
@CheckBoxGroup
private String petTypes;
----

In this example, all of the values retrieved from SampleStaticSource.getValues will be displayed as a collection of checkboxes.

.Using a url-based Source implementation to define a set of values
[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Values(url="CLIENT_ID/ORG/p/staticCodeValue/_search?fn=lookup&where=staticCodeValue.paramCode.eq('/petType')")
@CheckBoxGroup
private String petTypes;
----

In this example, all of the values retrieved from the url defined in **@Values** will be displayed
as a collection of checkboxes.

[discrete]
===== ValuesConditional

ValuesConditional is an extension capability provided by the framework. The annotation is used to conditionally set the @Values configuration for a dependent field
based on a SpEL condition. This annotation can be triggered for multiple events. Framework provides default event handling for this annotation on StateChange and StateLoad.

.ValuesConditional Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
| Name 			| Type			 | Default			 | Description

| target		| String		 | 					 | The target path relative to the this annotated field to update.
| condition		| Condition[]	 |					 | An array of conditional metadata that is responsible for determining whether or not the target field will be updated.
| resetOnChange	| boolean		 | true				 | When **true** and the associated _when_ expression evaluates to **true**, the _state_ of _target_ will be set to null. When **false** and the associated _when_ expression evaluates to **true**, the _state_ of _target_ will be set to null only when the previously existing _target_'s _state_ does not exist in the _then_'s **@Values** property. Otherwise, the existing _state_ will be preserved.
| exclusive		| boolean		 | true				 | Configures whether or not the first truthy condition should be exclusive. If true, then only the first truthy condition will be executed. If false then all truthy conditions will be executed. the default value is true.
|=========================================================

.Condition Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
| Name 			| Type			 | Default			 | Description

| when			| String		 | 					 | SpEL based condition to be evaluated relative to param's state on which this annotation is declared.
| then			| Values		 |					 | Values configuration to be applied to the param identified by the target path when this condition's when clause is found to be true.
|=========================================================

Consider the following sample defined Values:

[source,java,indent=0]
[subs="verbatim,attributes"]
.SampleValues.java
----
// Sample Values Implementations
public static class SRC_FOODS_ALL implements Source {
	@Override
	public List<ParamValue> getValues(String paramCode) {
		final List<ParamValue> values = new ArrayList<>();
		values.add(new ParamValue("Generic Food 1", "Generic Food 1"));
		values.add(new ParamValue("Generic Food 2", "Generic Food 2"));
		return values;
	}
}
public static class SRC_FOODS_DOG implements Source {
	@Override
	public List<ParamValue> getValues(String paramCode) {
		final List<ParamValue> values = new ArrayList<>();
		values.add(new ParamValue("Dog Food 1", "Dog Food 1"));
		return values;
	}
}
public static class SRC_FOODS_CAT implements Source {
	@Override
	public List<ParamValue> getValues(String paramCode) {
		final List<ParamValue> values = new ArrayList<>();
		values.add(new ParamValue("Cat Food 1", "Cat Food 1"));
		return values;
	}
}
----

Given a defined set of Values that we can assign using the @Values annotation, we can explicitly define conditions to set a dependent field's values.

[source,java,indent=0]
[subs="verbatim,attributes"]
.ValuesConditional.java
----
@Model
@Getter @Setter
public static class StatusForm {

	@ValuesConditional(target = "../petFoodSelection", condition = {
			@Condition(when = "state=='dog'", then = @Values(SRC_FOODS_DOG.class)),
			@Condition(when = "state=='cat'", then = @Values(SRC_FOODS_CAT.class)),
		}
	)
	@TextBox(postEventOnChange = true)
	private String petType;

	@Radio
	@Values(SRC_FOODS_ALL.class)
	private String petFoodSelection;
}
----

In this example, _petType_ is the field and _petFoodSelection_ is the dependent field. We set _petFoodSelection_ to contain the defaults ["Generic Food 1", "Generic Food 2"] initially and conditionally define those values when _petType_'s state is "dog" or "cat".

When the state of _petType_ is "dog", then the Values for _petFoodSelection_ will be ["Dog Food 1"]. Similarly when the state of _petType_ is "cat", then the Values for _petFoodSelection_ will be ["Cat Food 1"].

Conceptually speaking, we are *pushing* the updates of Values to the dependent field whenever the state of the annotated field loads or is changed.

[discrete]
==== ValuesConditionals
@ValuesConditionals is a collection of ValuesConditional calls.

The framework has the capability for a field to define ValuesConditional to affect multiple dependent fields.

.ValuesConditionals Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |ValuesConditional[] |  |

|=========================================================

[source,java,indent=0]
[subs="verbatim,attributes"]
.ValuesConditionals.java
----
@Model
@Getter @Setter
public static class StatusForm {

	@ValuesConditionals({
		@ValuesConditional(target = "../petFoodSelection", condition = {
				@Condition(when = "state=='dog'", then = @Values(SRC_FOODS_DOG.class)),
				@Condition(when = "state=='cat'", then = @Values(SRC_FOODS_CAT.class)),
			}
		),
		@ValuesConditional(target = "../petFoodSelection2", condition = {
				@Condition(when = "state=='dog'", then = @Values(SRC_FOODS_DOG.class)),
			}
		)
	})
	@TextBox(postEventOnChange = true)
	private String petType;

	@Radio
	@Values(SRC_FOODS_ALL.class)
	private String petFoodSelection;

	@Radio
	private String petFoodSelection2;
}
----

In this example, we have two dependent fields: _petFoodSelection_ and _petFoodSelection2_. Note that nothing has changed for the _petFoodSelection_ field from the previous example, but we have set a @ValuesConditional for the dependent field _petFoodSelection2_ that when the state of _status_ is "dog", the Values of _petFoodSelection2_ will be ["Dog Food 1"].
