
[discrete]
==== ConceptId

.ConceptId Attributes
[cols="3,^2,^2,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |String | "" | possible value for conceptId

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.ConceptId.java
----
@TextBox(postEventOnChange = true)
@ConceptId(value = "IOT1.1.1")
@Label(value = "If Other, provide reason")
private String otherReason;
----

[discrete]
==== Config

.Config Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|url |String |  |

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Config.java
----
@Config(url="/pageAddEditGoal/tileEditGoal/sectionEditGoal/goalDetailsForm/_nav?pageId=pageCarePlanSummary")
@Button(type = Button.Type.PLAIN)
private String cancel;
----

A class with @Config annotation is used to perform an action on button click.
In most cases, the action is to retrieve values via HTTP Rest calls
from database (MongoDB), and display on the web page. +

In the example shown above, when the button is clicked, the control will be navigated to the specified url. +
_nav_ is the http call for navigation. +

The possible Actions are: - +

 - get for HTTP GET
 - new for HTTP post
 - update for HTTP update
 - delete for HTTP delete
 - search for searching
 - nav for navigation
 - process for custom process/ work-flow definitions

[discrete]
===== Configs

.Configs Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|values |Config[] |  |

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Configs.java
----
@Configs({
@Config(url="~/client/org_name/_update"),
@Config(url="~/client/org_name/_process?fn=_set&url=/p/cmcase/_search?fn=query&where=cmcase.patientReferred.firstName.eq('<!/.m/patientReferred/firstName!>').and(cmcase.patientReferred.lastName.eq('<!/.m/patientReferred/lastName!>'))"),
@Config(url="~/client/org_name/_nav?pageId=vpAdvancedCaseSearch")
		})
@Button(type=Button.Type.PRIMARY, formReset=false)
private String submit;
----

@Configs is a collection of configuration calls. Multiple calls to the database
can be made simultaneously using @Configs, where each call will be represented by @Config. +

As shown in the example, when the submit button is clicked, three http calls that are being made viz.
update, process, and navigation.

[discrete]
==== ConfigNature

[discrete]
===== Ignore

Framework persists the data objects of a class in database using @Repo by serializing the class and associating a version number that is called seriaVersionUID.
However, if we do not want the framwework to serialize for time being, we can use @Ignore component of ConfigNature class. The following example shows that: -

[source,java,indent=0]
[subs="verbatim,attributes"]
.StartsWith.java
----
@Domain(value="patient", includeListeners={ListenerType.persistence})
@Repo(value=Database.rep_mongodb, cache=Cache.rep_device)
@ToString
public class Patient extends IdString {

	@Ignore
	private static final long serialVersionUID = 1L;

	}
----

[discrete]
==== Domain

Core Config configuration @Domain annotation persists data. +

Core config @Domain will always be followed by @Repo that will specify the way data is persisted. +

*includeListeners={ListenerType.persistence, ListenerType.update}* of @Domain
specifies that the data will be persisted. +
*value=Database.rep_mongodb* of @Repo specifies that a class with
@Domain annotation will use MongoDb for persistence.


[source,java,indent=0]
[subs="verbatim,attributes"]
.Domain.java
----
@Domain(value="cmcase", includeListeners={ListenerType.persistence, ListenerType.update})
@Repo(value=Database.rep_mongodb, cache=Cache.rep_device)
public class CMCase extends IdString {
}
----

NOTE: Please read @Repo for mroe information regarding @Repo annotation.

[discrete]
==== DomainMeta

Similar to ViewStyle component, DomainMeta component is used to define an ANNOTATION_TYPE level annotation that is used with few view config annotations,
as follows: - +

 - @ConceptId


[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Retention(RetentionPolicy.RUNTIME)
	@Target(value={ElementType.ANNOTATION_TYPE})
	@Inherited
	public @interface DomainMeta {

	}
----

Here is an example: -

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Retention(RetentionPolicy.RUNTIME)
	@Target({ElementType.FIELD})
	@DomainMeta
	public @interface ConceptId {
		String value() default "";
	}
----


[discrete]
==== Execution
Execution is inherited annotation for @Config and @KeyValue. It is not currently being directly used, but is there for hieracrchial purposes.

More documentation will be added here if Execution expands or is directly used.

[discrete]
==== Initialize

.Initialize Attributes
[cols="3,^2,^2,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|alias |String | initialize | cannot be changed

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Initialize.java
----
@Section
@Initialize
@Config(url="/vpAdvancedMemberSearch/vtAdvancedMemberSearch/vsMemberSearchCriteria/vfAdvMemberSearch/_process?fn=_setByRule&rule=updateadvmbrsearchcriteria")
private VSMemberSearchCriteria vsMemberSearchCriteria;
----

[discrete]
==== MapsTo

[discrete]
===== Path

.Path Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |String |  |specify value of Path
|colElemPath |String | DEFAULT_COL_ELEM_PATH | specifies column element path
|state |State | State.Internal | specifie path state
|linked |boolean |true | determine if the path has links
|cache |Cache | Cache.rep_device | specifies cache type

|=========================================================

[source,java,indent=0]
[subs="verbatim,attributes"]
.Path.java
----
@Path()
private Long version;
----

[discrete]
===== Type

.Type Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |class<?> | |
|silent |boolean | true |determines if Type is silent

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Type.java
----
@MapsTo.Type(CMCase.class)
public static class SectionEditGoal  {
    }
----

NOTE: If it is not mapped _(@Mapped)_, an exception will be thrown. +
If no exception is thrown, defaults to silent.

[discrete]
==== Mode

.Mode Attributes
[cols="3,^2,^2,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |enum | Options.INHERIT | OPtions of Mode

|=========================================================

NOTE: The possible Property enum values for value are *INHERIT, READONLY, HIDDEN*

[discrete]
==== Model

[discrete]
===== Param

.Param Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|value |Class<? extends Source> | Source.class |specify value of Path
|url |String | staticCodeValue | specifies url

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.Param.java
----
@Model.Param.Values(url="~/client/orgname/staticCodeValue/_search?fn=lookup&where=staticCodeValue.paramCode.eq('/thisIsParentQuestion14')")
@Radio(postEventOnChange=true, controlId = "27")
private String thisIsParentQuestion14;
----

NOTE: The example will retrieve the value of Radio button from the specified url. +
*staticCodeValue* is a collection in MongoDB that will be searched and retrieved using @Model annotation.
The search criteria is specified using param code _thisIsParentQuestion14_

[discrete]
===== Text

.Text Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|label |String | |

|=========================================================

[discrete]
==== ParamContext

**@ParamContext** is used to set the contextual properties of a field during the _OnStateLoad_ event (e.g. _visible_, _enabled_).

.ParamContext Attributes
[cols="3, 3, 3, 10",options="header"]
|=========================================================
| Name 			| Type			| Default	 | Description

| visible		| boolean		| 			 | Whether or not the decorated target should be visible.
| enabled		| boolean		|			 | Whether or not the decorated target should be enabled.
|=========================================================

The intent of **@ParamContext** is to be able to decorate fields to define default contextual behavior. For example:

[source,java,indent=0]
[subs="verbatim,attributes"]
.SampleView.java
----
 public static class SampleView {

    @TextBox
    @ParamContext(enabled=false, visible=false)
    private String myTextBox;
 }
----

In this scenario we have configured the contextual values for _enabled_ and _visible_ to be **false** for _myTextBox_. These values will
be set during the _OnStateLoad_ event and _myTextBox_ consequently will not be enabled or visible when the corresponding page is rendered.

TIP: **@ParamContext** can also be defined on annotations. In these scenarios when a field is decorated with that annotation, then the
handler for **@ParamContext** will execute. This may be useful when building a framework extension.

[discrete]
==== SearchNature

[discrete]
===== StartsWith

This component is ued to validate a field. The wilcard attribute determines the validation criteria for a field. This is a server side component.

.StartsWith Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description

|wildCard |String | * |determines the search criteria

|=========================================================


[source,java,indent=0]
[subs="verbatim,attributes"]
.StartsWith.java
----
@NotNull
@StartsWith
@Label(value = "First Name")
private String firstName;
----

NOTE: The example will always search the first name that starts with anything, represented with the default value. A specific search criteria can be
specified using wildcard attribute of @StartsWith.

[discrete]
==== Repo

.Repo Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
|Name | Type |Default |Description
|alias |String | | cannot be changed
|value |enum |  |specify value of Path
|cache |enum | Cache.rep_device | specifies cache type
|autoSave |boolean |true | determine if the autosave is enabled

|=========================================================

NOTE: The possible enum values for value are *DATABASE.rep_none, DATABASE.rep_rdbms, DATABASE.rep_mongodb, DATABASE.rep_ws* +
The possible enum values for cache are *CACHE.rep_none, CACHE.rep_device*

@Repo is used to determine where the data will be persisted. It is always used along with @Domain. +

[discrete]
===== rep_mongodb

The following example shows how data is persisted/ retrieved using MongoDB as a source.


[source,java,indent=0]
[subs="verbatim,attributes"]
.Repo.java
----
@Domain(value="cmassessment", includeListeners={ListenerType.persistence})
@Repo(alias="cmassessment",value=Database.rep_mongodb, cache=Cache.rep_device)
@Getter @Setter
public class CMAssessment extends IdString {
}
----

[discrete]
===== rep_ws

Databse values can be persisted/ retrieved not only using internal MongoDb as a source, we can now use an external web service for the same purpose.
All we have to do is create a REST call to a web service that will provide or store the data. Following is an example: -


[source,java,indent=0]
[subs="verbatim,attributes"]
.ExtClient.java
----
@Domain(value="ext_client")
@Repo(value=Database.rep_ws, cache=Cache.rep_device)
@Getter @Setter @ToString(callSuper=true)
public class ExtClient {

}
----

Notice *@Repo(value=Database.rep_ws)* in the code above. This indicates that it will make use of an external web service call rather than
a MongoDb call for ExtClient data objects' persistence/ retrieval purposes.

The advantage of this feature is that now we do not rely on internal source only. This gives us better flexibility and maintainability

[discrete]
==== Rule

@Rule allows its decorated field a mechanism for triggering one or more rule definitions during its OnStateLoad and OnStateChange events.

[source,java,indent=0]
[subs="verbatim,attributes"]
.SampleRuleEntity.java
----
@Domain(value="sample_rule_entity", includeListeners={ListenerType.persistence})
@Repo(Database.rep_mongodb)
@Getter @Setter
public class SampleRuleEntity {

	// Execute the rule at "rules/sample_increment" during the OnStateLoad and
	// OnStateChange events of ruleParam.
	@Rule("rules/sample_increment")
	private String rule_param;
}
----

By default, the framework provides support for firing all rules for a given domain entity. That is, for the *SampleRuleEntity.java* above we might have a rule file defined as *sample_rule_entity.drl* which will be automatically fired by naming convention.

For cases where additional configuration for other rules is needed, @Rule can be used.

.Rule Attributes
[cols="4,^3,^3,10",options="header"]
|=========================================================
| Name 			| Type			 | Default			 | Description

| value			| String[]		 | 					 | rule file path(s) to execute.
|=========================================================

[discrete]
==== Values
Values provides a mechanism for populating a fields _values_ property. This can be used by a number of components
to perform such functions as: define a set of selections for radio buttons and checkboxes, or populating a dropdown list.

.Values Attributes
[cols="3, 5, 3, 10",options="header"]
|=========================================================
| Name 			| Type			 				| Default			 | Description

| value			| Class<? extends Source>		| EMPTY				 | Source implementation that returns a list of **ParamValues**
| url			| String						|					 | url endpoint that returns a list of **ParamValues**
|=========================================================

NOTE: _value_'s default value is **EMPTY**, which is a simple Source implementation that returns an empty list of **ParamValues**.

[discrete]
===== Source
The Source is a simple abstraction for providing a contract between implementations to provide data to the framework.

Source is exclusively used for **@Values**.

[source,java,indent=0]
[subs="verbatim,attributes"]
.Source.java
----
public static interface Source {
	public List<ParamValue> getValues(String paramCode);
}
----

We can use this to define several different types of values providers. A simple static Source implementation is shown below:

[source,java,indent=0]
[subs="verbatim,attributes"]
.SampleStaticSource.java
----
public class SampleStaticSource implements Source {
	public List<ParamValue> getValues(String paramCode) {
		List<ParamValue> values = new ArrayList();
		values.add(new ParamValue("sample.value.1", "Sample Value 1"));
		return values;
	}
}
----

[discrete]
===== Examples

.Using a static Source implementation to define a set of values
[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Values(SampleStaticSource.class)
@CheckBoxGroup
private String petTypes;
----

In this example, all of the values retrieved from SampleStaticSource.getValues will be displayed as a collection of checkboxes.

.Using a url-based Source implementation to define a set of values
[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Values(url="CLIENT_ID/ORG/p/staticCodeValue/_search?fn=lookup&where=staticCodeValue.paramCode.eq('/petType')")
@CheckBoxGroup
private String petTypes;
----

In this example, all of the values retrieved from the url defined in **@Values** will be displayed
as a collection of checkboxes.

[discrete]
==== ViewParamBehavior Component

Similar to ViewStyle component, ViewParamBehavior component is used to define an ANNOTATION_TYPE level annotation that is used with few view config annotations,
as follows: - +

 - @Hints
 - @Initialize
 - @Mode
 - @PageHeader
 - @PageFooter


[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Retention(RetentionPolicy.RUNTIME)
	@Target(value={ElementType.ANNOTATION_TYPE})
	@Inherited
	public @interface ViewParamBehavior {

	}
----

Here is an example: -

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Retention(RetentionPolicy.RUNTIME)
	@Target({ElementType.FIELD})
	@ViewParamBehavior
	public @interface Initialize {
		String alias() default "initialize";
	}
----


[discrete]
==== ViewStyle Component

ViewParamBehavior component is used to define an ANNOTATION_TYPE level annotation that is used with
all most of the annotations described below.


[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Retention(RetentionPolicy.RUNTIME)
	@Target(value={ElementType.ANNOTATION_TYPE})
	@Inherited
	public @interface ViewStyle {

	}
----

NOTE: The above code is the definition if ViewStyle component. As you can see, ElementType.ANNOTATION_TYPE determines that this annotation can only be used
in other annotations.

Here is an example: -

[source,java,indent=0]
[subs="verbatim,attributes"]
----
@Retention(RetentionPolicy.RUNTIME)
	@Target({ElementType.TYPE})
	@ViewStyle
	public @interface ViewRoot {
		String alias() default "root";
		String layout() default "";
	}
----