[[release-notes-1.3.0.M3]]
= 1.3.0.M3

NOTE: All changes introduced between `1.2.0.M3` from `1.2.0.M4` have also been migrated in this version. Please see the link:1.2.0.x.html#release-notes-1.2.0.M4[1.2.0.M4] release notes for more details.

* **General Changes**
** Test support changes
*** Added new method: `MultiOutput#findFirstParamOutputEndingWithPath(String path)`
*** Added new method: `MultiOutput#findParamOutputsEndingWithPath(String path)`
*** Modified `ParamUtils#convertToStringPayload(Object payload)` to transform `String` types to their JSON equivalent. (e.g. the string `foo` should be transformed to `"foo"`)

* **Core Config Annotations**
** Added a null safety check for `@Grid` label creation of a non complex entity.

* **View Config Annotations**
** N/A

* **Bug Fixes**
** Fixed an issue with `@Grid` row expander where the expander icon was not being reset after receiving an update from the server.
** Fixed an issue where calling a `URLBasedFunctionHandler` with `url` starting with a domain alias with `"/p"`, like: `"/petclinic"` was inappropriately doing a cross domain fetch.